### ISSUE TITLE
What is the purpose of importing T0

### ISSUE THREAD

**Issue by reza-ghazi** [skyfielders/python-skyfield#1018]
Hello,

Could you please explain the purpose of the import of **`T0`** in the following section:

[Proper motion and parallax](https://rhodesmill.org/skyfield/stars.html#proper-motion-and-parallax)

Thank you,

**Comment by brandon-rhodes** [comment]
It was left over from an earlier version of that documentation, that illustrated the `epoch` keyword on the first star with `epoch=T0`. Since that argument has since been removed from the example, I have removed the unused import too. The documentation online will update the next time a new Skyfield is released.

**Comment by reza-ghazi** [comment]
Thank you.
