### ISSUE TITLE
Polar Motion link should be updated

### ISSUE THREAD

**Issue by reza-ghazi** [skyfielders/python-skyfield#1019]
Hello,

When I run the code in the following section:

[Polar Motion](https://rhodesmill.org/skyfield/accuracy-efficiency.html#polar-motion-1)

I will get the following error:

```bash
OSError: cannot download ftp://ftp.iers.org/products/eop/rapid/standard/finals2000A.all because <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>
```

The file `finals2000A.all` has moved to [IERS https data download](https://datacenter.iers.org/products/eop/rapid/standard/)

For now, we can download the file manually.

**Comment by brandon-rhodes** [comment]
Now that three weeks have passed (holidays and such intervened), I can confirm that the site is still down and is raising `[Errno 111] Connection refused` for me, too. The last time this issue came up, about two and a half years ago, a Skyfield user reported a personal conversation with someone at IERS who encouraged us to keep using FTP:

> I spoke with someone at IERS in Frankfurt who assured me that the ftp.iers.org server should be the primary choice for downloading EOP data. He also reminded me that although the USNO server (maia.usno.navy.mil) is up and running, the last time it was down it took 2.5 years to bring it back online. So I agree that Skyfield should stick only to the official download URL.

— https://github.com/skyfielders/python-skyfield/issues/730#issuecomment-1107833502

As noted in the discussion of that issue, the official web server `maia.usno.navy.mil`, which tends to be down for years at a time, also has the liability that some countries cannot connect because of sanctions enforced for servers with `.mil` domain names. At the moment it seems to be up and has a [page offering Bulletin A data](https://maia.usno.navy.mil/products/bulletin-a).

I am intrigued by your offering a URL to `datacenter.iers.org` — I've only seen that hostname a few times, and never in an official setting, but I note that it's not `.mil` and thus wouldn't be a problem (presumably?) for any Skyfield users. Is there any official announcement about its support and availability?

(Oddly enough, I see the claim at the top of #732 that Skyfield was already using `datacenter.iers.org`, but I can't confirm that by looking through the version history?)
