### ISSUE TITLE
Run offline with uniform timescale?

### ISSUE THREAD

**Issue by uhoh-SE** [skyfielders/python-skyfield#105]
In [this answer][1] I mentioned that one needs to be connected to the internet the first time to download an ephemeris (and other things), and then Skyfield will run off line - for a while.

If someone wanted to access all of Skyfield's features but was willing to give up automatic checking for leap seconds and either had some work-around, or just could live with it, is there some way - any way - that Skyfield be run long-term off-line*?

I understand that a very appropriate answer might be along the lines of "even if there were, it would be bad to do that, so *just say no!*"

It looks like it's always necessary to use `ts` but there is no way to convince it to keep working if the leap second info is out of date by more than Skyfield's internal grace period.

(*) imagine just for example a solar/battery powered Raspberry Pi that points a mirror such that moonlight passes through a window and down a hallway whenever it's possible. That's a piece of cake with Skyfield, but it would still currently require an internet connection if I understand correctly.

[1]: http://astronomy.stackexchange.com/a/17946/7982

**Comment by brandon-rhodes** [comment]
Alas — I added such logic back and documented it back in July (see 267f0038f29b45bf72a8eb960151d391f49e2ca0), but I have not released a new Skyfield since then to let people start using an offline mode!

I will run through the open issues and pull requests today and try to get a release out by this evening. In the meantime, you can use the new features described in the above commit immediately by running:

    pip install https://github.com/skyfielders/python-skyfield/archive/master.zip

Let me know if the new feature works as you expect!
