### ISSUE TITLE
Finding the circumpolar circle

### ISSUE THREAD

**Issue by tcz** [skyfielders/python-skyfield#109]
This is a question about usage: I'd like to draw the circumpolar circle from a certain point on the surface of Earth. I'm wondering if this is possible to do with skyfield (that is, finding the location of the circle).

**Comment by barrycarter** [comment]
The circumpolar circle at latitude L is simply the declination line 90-L (in degrees).

**Comment by tcz** [comment]
Sorry, I'm not sure I'm following. Don't I need to find the celestial pole first?

**Comment by davidmikolas** [comment]
@barrycarter Precession & Nutation? I'm not sure if the _current axis of the Earth_ is exactly perpendicular to the "z axis" in Skyfield's coordinate system.

**Comment by brandon-rhodes** [comment]
@tcz Where are you planning on drawing the circle — on what kind of plot, and against what kind of coordinate system governing the plot? The answer will be different depending on what kind of coordinate needs to be the input to the plot.

**Comment by tcz** [comment]
I'm drawing a sky map with a stereographic projection, picturing the whole
visible celestial hemisphere from a certain surface point on the Earth (and
a certain time). I am using right ascension and declination data (and other
information) of stellar objects and convert them to apparent position on
the sky (altitude, azimuth) using Skyfield.

**Comment by brandon-rhodes** [comment]
To draw a circumpolar circle around the J2000 pole, you could create a few hundred  `Star` objects evenly spaced at RAs from 0h through 24h and at the declination where you want the circle. Compute their positions and coordinates on your diagram, and then draw lines between them to create the circle.

For circumpolar circles around poles of other years besides J2000, you will need to apply a rotation because the dynamical coordinate system changes each year. I wonder if Skyfield should in the future include a method that makes it easy to turn RA and dec values for different years into pure ICRS coordinates?

**Comment by barrycarter** [comment]
I was actually aware of nutation/precession when I wrote my answer, but was hoping my answer would be accurate enough and no one would catch me out :)

My http://astronomy.stackexchange.com/a/13009/21 may or may not be helpful.

Brandon, re your wondering, yes, yes it should :)

**Comment by barrycarter** [comment]
If you need exceptionally high precision https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/ may help. Be sure to read the aareadme.txt file for details.

**Comment by brandon-rhodes** [comment]
@tcz — As far as I know, the approach I suggested (approximating the circle with points distributed in a ring around the celestial pole) should let you draw a circumpolar circle with as high an accuracy as you would like to achieve. So I am going to tentatively close this issue for now as solved. But please re-open if you have further questions or problems with your diagram!
