### ISSUE TITLE
Time Cutoff error 

### ISSUE THREAD

**Issue by wanglikun1973** [skyfielders/python-skyfield#113]
When I print 
ts = load.timescale()
print(ts.utc(2014, 01, 18, 1, 35, 37).utc)

it shows, 
(2014, 1, 18, 1, 35, 36.999982595443726)

I think there are some cut off errors. It should return as 
(2014, 1, 18, 1, 35, 37)

Please check. Thank you for your help,

**Comment by davidmikolas** [comment]
@wanglikun1973  I think this is expected behavior - floats are 64 bits, with 52 bits for the mantissa. 

See http://docs.scipy.org/doc/numpy/user/basics.types.html

![screen shot 2016-10-12 at 1 49 12 pm](https://cloud.githubusercontent.com/assets/17236804/19298779/e34ffad6-9082-11e6-9f0c-14a9aad45b22.png)

This is just the granularity of float64 numbers. I ran into this problem earlier, see the question and all the answers here: http://stackoverflow.com/a/36380163/3904031

If you take a big ephemeris time span, say 6000 years expressed in microseconds, and divide by 2 to the 52, you get about 40 microseconds, which is what the plot shows.

    6000*365.25*24*3600 * 1E+06 / 2**52  ~ 42.0

Here's a quick result, script shown below it:

![screen shot 2016-10-12 at 1 44 17 pm](https://cloud.githubusercontent.com/assets/17236804/19298848/41b8283c-9083-11e6-9289-b2edd9f249ac.png)

    import numpy as np
    import matplotlib.pyplot as plt
    from skyfield.api import load

    data = load('de421.bsp')
    ts   = load.timescale()

    micros = 1E-06 * np.arange(1001)  # zero to 1000 microseconds

    time = ts.utc(2014, 01, 18, 1, 35, 37+micros)

    plt.figure()
    plt.plot(micros, time.tt-time.tt[0])
    plt.show()

**Comment by wanglikun1973** [comment]
from skyfield.api import load, utc
from datetime import datetime, timedelta, tzinfo
from astropy.time import Time

ts = load.timescale()
t1 = ts.utc(2014, 01, 18, 1, 35, 37)
t2 = Time(datetime(2014, 01, 18, 1, 35, 37), scale='utc')
print(t1.ut1 - t2.ut1.jd)*24*60*60
-0.0013679265976

I compared two codes from skyfield and astropy.time to retrieve UT1, it gives two different values. Because JD_UT1 is used as input for many computation,  using two different values as inputs does cause the differences.  I  wonder which one is more accurate? Thanks, 

Likun~

**Comment by davidmikolas** [comment]
OK that's a different question. Maybe you should rename this issue to include this or better yet start a new issue. The original 'time cutoff' seems to be the lowest bit roundoff in float64 and under 40 microseconds. This new 1.3 milliseconds difference between Skyfield and Astropy is probably something that should be flagged more appropriately. I don't have Astropy, but you might do the same kind of test to see if it's still LSB in Astropy.

Skyfield uses JPL ephemerides and those only span several thousands of years. Maybe Astropy is set up for longer time ranges so the LSB is larger?

**Comment by brandon-rhodes** [comment]
The official data sources that are driving the UT1 estimate in Skyfield and in AstrpPy do not, themselves, necessary predict what UT1 was at that time and date, but at some frequency that provides point-values at moments somewhere around that date. So:

1. The difference could be in the downloaded data sources, either in their resolution, or in their being quite different values.
2. The difference could be that the data is the same, but that the interpolation needed to turn the adjacent data points into an estimate for that specific moment you are asking about is a different technique in each of the two libraries.

You can check out `interpolate_delta_t()` to see the way Skyfield does it, which I think is simple linear interpolation at this moment. Maybe AstroPy does something fancier?

**Comment by brandon-rhodes** [comment]
I've left this issue dangling for too long, without a good explanation in the documentation of floating point precision! Thanks, @davidmikolas, for your early answers to this issue.

@wanglikun1973, the docs now explain the situation, so that folks don't have to visit an issue like this one to learn about floating point precision, so feel free to point folks here who might also have this question:

http://rhodesmill.org/skyfield/time.html#time-precision-is-around-20-1-s

Thanks for your interest in Skyfield.
