### ISSUE TITLE
Optional deflection in apparent position

### ISSUE THREAD

**Issue by tcz** [skyfielders/python-skyfield#114]
Calculating deflection takes a lot of time when getting apparent position of a sky object. While definitely a nice feature and much needed for some applications, for my purposes (drawing a simple sky map) is not necessary (how much do sky object deflect? i presume not much).

I'm proposing making deflection calculation optional. Something like:

```
earth.at(t).observe(mars).apparent(deflection=False)
```

**Comment by tcz** [comment]
Just for perspective: manually commenting out the `add_deflection` line reduced my script's execution time by 70%.

**Comment by brandon-rhodes** [comment]
Aberration is also a very small effect, and is also not included when making professional sky maps — have you tried not calling `apparent()` and seeing whether the resulting coordinates still give you a good sky map?

**Comment by tcz** [comment]
I still need the apparent position because I'm rendering maps from a
particular position on Earth.

**Comment by brandon-rhodes** [comment]
For the moment, while I weigh the keyword-argument option you propose, here is how you can go ahead and skip the step using Skyfield today:
```
apparent = Apparent(astrometric.position.au, astrometric.velocity.au_per_d)
apparent.observer = astrometric.observer
```
Let me know whether this approach works — it just grabs the position and velocity and observer (yes, the final item of the three has to be awkwardly set manually, because, as you can see, I am still ironing out a clean interface here) and stuffs those vectors into a new Apparent object. But I think the code should work — try it and let me know. Thanks!

**Comment by tcz** [comment]
That has worked beautifully! Thank you!

**Comment by brandon-rhodes** [comment]
For now I am going to close this since an easy workaround exists, but I'll continue thinking about it and whether methods like `apparent()` that do several steps should be parameterized so that users can reach in and turn everything on and off, or whether there should instead be alternative methods they can call do to the steps. Thanks for alerting me to this use case!
