### ISSUE TITLE
Make a 0.9.1 release?

### ISSUE THREAD

**Issue by pkgw** [skyfielders/python-skyfield#120]
The most recently released version of Skyfield is not compatible with Python 2.7 because of the now-fixed issue #119. If it's not much effort, it would be nice packaging-wise to have a 0.9.1 point release that incorporated this fix.

**Comment by brandon-rhodes** [comment]
You are right, a new release will not be much trouble — I will try putting it on my to-do list. Out of curiosity, what has led you to call the `usno_historic_delta_t()` function? It is an internal function that does not even work with a normal Skyfield install, since Pandas is not a Skyfield dependency, and is not intended to be needed in normal operation.

**Comment by pkgw** [comment]
Nothing, but the `setup.py install` step tries to byte-compile all source files, and in so doing it dies of a `SyntaxError` in that file.

**Comment by brandon-rhodes** [comment]
Ack! I had forgotten about that — yes, makes the error relevant to many users! I will aim to get a new version out this weekend if not earlier.

**Comment by brandon-rhodes** [comment]
There was an unexpected delay, but the new version 0.9.1 is now released and on PyPI. Thanks again for the idea!
