### ISSUE TITLE
Add "epoch of position" parameter for stars

### ISSUE THREAD

**Issue by pkgw** [skyfielders/python-skyfield#125]
Sometimes the positional information that you have for a celestial object is anchored to an epoch other than J2000.0. This matters if the object has a non-zero proper motion or parallax.

As far as I can tell, Skyfield doesn't support "epochs of position" other than J2000.0. It would be nice to add this — I think it's just a matter of wiring in some parameters in `starlib.py` that would replace `T0`. I can prepare a PR for this if there's interest.

**Comment by brandon-rhodes** [comment]
Good point! We should broaden Skyfield’s support for other epochs. Right now, the only code that adapts coordinates in one epoch to the J2000.0 epoch that Skyfield uses internally is an obscure function in a work-in-progress module that adapts Hipparcos records, whose proper motion is referred to J1991.25, to J2000.0.

The Skyfield routine, like much of Skyfield, is based on the USNO’s work in their NOVAS library. Search for the `transform_hip` routine’s description in their documentation:

http://aa.usno.navy.mil/software/novas/novas_c/NOVAS_C3.1_Guide.pdf

and then in their C code:

http://aa.usno.navy.mil/software/novas/novas_c/novas.c

If you want all the details. The Skyfield routine that does the same thing lives in:

https://github.com/skyfielders/python-skyfield/blob/master/skyfield/data/hipparcos.py

The code should certainly be generalized to handle input coordinates whose proper motion is from other epochs besides the exact epoch used by Hipparcos. In addition, I suppose people might want a convenient way to import catalogs whose coordinate epoch is not J2000.0?

Do you have specific catalogs of your own that you were wanting to import, that we could target specifically?

**Comment by pkgw** [comment]
I'm running into this when computing present-day apparent positions for sources in the 2MASS catalog, since their astrometry is referenced to the date when they were observed. The 2MASS source catalog comes with a `Date` observation that gives that information.

I guess I was envisioning that the `Star` class would acquire a new property, something like `epoch_of_position`, that would default to J2000.0. Then the uses of `T0` in [Star._observe_from_bcrs](https://github.com/skyfielders/python-skyfield/blob/master/skyfield/starlib.py#L79) would just use `self.epoch_of_position` instead. I have an intuitive feeling that this would be a bit nicer way to do things than by a one-time operation that "corrects" records à la the Hipparcos code, since it preserves more information. But that's certainly not a deeply-considered stance.

**Comment by brandon-rhodes** [comment]
I was using the convert-everything-to-ICRF because that was the approach of the NOVAS library whose logic I copied to create most of Skyfield. I'll look back at the stars code now that PyCon is over and see whether it would make sense to abandon that position or not!

**Comment by pkgw** [comment]
It's been a while but I've corresponded with the NOVAS authors about an epoch-of-position parameter since NOVAS doesn't have such a thing either, and for what it's worth my general takeaway was that they thought it would be a useful thing to have.

**Comment by brandon-rhodes** [comment]
I am reopening this issue and now believe your suggestion is a good one. Two recent developments have made it especially relevant:

1. I am now planning to introduce the pattern of loading star catalogs as Pandas dataframes, because it makes the code so simple. Pandas routines like `read_fwf()` make reading in a typical star catalog trivial, and Pandas filters then make it easy to filter stars by magnitude before plotting them.
2. Because the numbers in a dataframe are easy for users to inspect, I think it will cause confusion if a user loads a catalog like Hipparcus, prints out the row for a familiar star, and sees a different RA and dec than the one loaded from the catalog because Skyfield has auto-adjusted the positions to epoch J2000. Instead, I should keep the numbers the same as in the catalog itself until the user asks for where the stars are `at()` a given time.

**Comment by brandon-rhodes** [comment]
Oh ­— ahem. Someone did this back in #166 and I entirely forgot. Ignore my re-opening of this old issue!
