### ISSUE TITLE
Reading de200 ephemeris file

### ISSUE THREAD

**Issue by tanul** [skyfielders/python-skyfield#132]
Hi
I am currently working on reproducing barycentric correction of RXTE data in python. For this I have to work with DE200.bsp ephemeris file. DE200 is referred to the dynamical equator and equinox of 2000 (FK5). Skyfield calculates position in ICRS by default. My question is when sky field returns position using DE200, the returned positions are in FK5 or ICRS.

I believe this is not the page where I should ask my queries. But I was not able to find a page to contact you. Please help me in resolving this issue.

Regards
Tanul

**Comment by brandon-rhodes** [comment]
Skyfield treats the FK5 and ICRS as the same coordinate system, since the ICRS was intended to have axes that point in the same direction but that are specified to higher precision. So you will see that the `skyfield/data/spice.py` file specifies a conversion matrix for FK4, but not for FK5 because no conversion is necessary. So please go ahead and treat the two as equivalent. And I hope you make good progress on your project!
