### ISSUE TITLE
load.tle caching issues

### ISSUE THREAD

**Issue by darkstar007** [skyfielders/python-skyfield#138]
The load.tle cache appears to only look at the filename, and not the complete URL. So the following code:
```
from skyfield.api import Topos, load

stations_url = 'http://celestrak.com/NORAD/elements/cubesat.txt'
satellites = load.tle(stations_url, reload=True)
satellite = satellites['STRAND-1']
print(satellite)

stations_url2 = 'file:///home/matt/ephem_data_raw/ephem_20170410/cubesat.txt'
satellites2 = load.tle(stations_url2, reload=True)
satellite2 = satellites2['STRAND-1']
print(satellite2)
```

outputs:

```
EarthSatellite u'STRAND-1' number=39090 epoch=2017-05-09T12:46:26Z
EarthSatellite u'STRAND-1' number=39090 epoch=2017-05-09T12:46:26Z
```

which is wrong considering one of the files is from April (and should give the answer of 207-04-08....). I'm not getting any progress bar so its not even attempting to load the 2nd file. This caching behaviour of just using the filename as the key certainly isn't desirable in my opinion.

Also, I assumed the **undocumented** reload argument would force a reload, but it appears to do nothing.

Thanks,

Matt

**Comment by brandon-rhodes** [comment]
Thanks very much for this report! Though other projects limited the amount of time I could spend on Skyfield, I'm awake in the middle of the night so I'm finally tackling this issue.

* The reload argument had good intentions, but the routine it was calling reversed its effect unintentionally! I'm patching it to work correctly.
* I'm adding a `filename=` to `load.tle()` so that you can specify alternative local filenames.

Hopefully that will address your interesting use case of two URLs with the same filename at the end!
