### ISSUE TITLE
timescale ignores Loader(path) information when refreshing a stale LeapSecond file

### ISSUE THREAD

**Issue by bwgref** [skyfielders/python-skyfield#140]
Just noticed that once. Finally figured out that's why it was continuing to download new LeapSecond files even though some exist. Only problem is that it seems to put them in the current working directory rather than in the local path specified by Loader.

Not sure where in the code to poke at that, but I may come back and submit a PR for a fix if I can confirm that's what's going on.

**Comment by brandon-rhodes** [comment]
I'll see if I can track the problem down. Thanks for the report!

**Comment by brandon-rhodes** [comment]
I haven't yet observed this myself. Could it have been due to Earth satellites downloading timescales using their own loader — a terrible behavior that I've just removed? I'm going to close this for now, pending more reports of this symptom. Please feel free to re-open if the new version of Skyfield 1.6 that I'll soon release shows this same problem for you!
