### ISSUE TITLE
Feature request: make Skyfield able to load Stellarium FAB files

### ISSUE THREAD

**Issue by ghost** [skyfielders/python-skyfield#143]
Stellarium 0.16.1 lists over 750 named stars in stellarium-0.16.1/skycultures/western/star_names.fab. I am requesting these be added to named_stars.py

This request inspired by https://github.com/brandon-rhodes/pyephem/pull/128

Note that the list does contain "duplicates" because double stars are listed like this (example):

```
 72603|_("Zubenelgenubi I") 1,2,6,11
 72603|_("Zubenelgenubi")
 72622|_("Zubenelgenubi II") 1,2,6,11,12
 72622|_("Zubenelgenubi")
```
However, these are resolvable.

[star_names.fab](https://github.com/skyfielders/python-skyfield/files/1404126/temp.txt)

**Comment by brandon-rhodes** [comment]
I am not sure, but will think about the proposal — whether Skyfield itself should get larger to have onboard data sets for unofficial star names. (Or is there an official source better than Stellarium giving these as official names?) Looking over the list, most of the names are obscure enough that I've never seen them anywhere. If we could find a data source for this, maybe it would make sense for Skyfield to gain a function that knew how to import these `.fab` files? Then, instead of Skyfield itself having to decide how many of the https://github.com/Stellarium/stellarium/tree/master/skycultures star name files to include and duplicate from the Stellarium project, interested users could instead import the names into Skyfield directly from a checkout of the Stellarium project.

Would that resolve your use case? What were you planning to do with these star names in your code?

**Comment by barrycarter** [comment]
This is a bit embarrassing, but I don't use Skyfield or even Python myself. 
 
However, since I believe you want to make Skyfield as "complete" as 
possible, adding star names would be useful. Additionally, it might 
help others, and, of course, I may one day use it myself. 
 
I was actually inspired by 
https://github.com/brandon-rhodes/pyephem/pull/128 where you add stars 
to pyephem, skyfield's predecessor of sorts. 
 
It turns out only 227 stars have official IAU-recognized names: 
https://www.iau.org/public/themes/naming_stars/ and I definitely think 
these should be included. 
 
Unfortunately, I couldn't find a canonical source for the rest of the 
names. http://www.pas.rochester.edu/~emamajek/WGSN/IAU-CSN.txt has a 
list of 310 stars, but with an explicit disclaimer that the IAU list 
is "more" canonical (though it should be identical). 
 
Based on this, I agree: having a mechanism to load Stellarium FAB 
files (regardless of how they're produced) would be a better idea.
