### ISSUE TITLE
Feature request: planets arrays

### ISSUE THREAD

**Issue by gyth** [skyfielders/python-skyfield#154]
useful precision: my common used languages are neither English nor  python.
i like the way Date arrays are usable in this wonderful library.

is there any way to accept an array of planet/body to be computed at a given time ?
would it be nice if the following code could work
```python
#!/usr/bin/python
#skyfield 1.1

from skyfield.api import load, now
ts = load.timescale()
jd = ts.now()
planets = load('de421.bsp')

earth = planets['earth']
multiplanet = planets['moon','sun']

positions = earth.at(jd).observe(multiplanet)

print(positions.distance().m) # result :  [  3.57409219e+08   1.47099740e+11]
```
i guess in this case skyfield code would probably benefit from some sort of caching mechanism to decrease the calculating weight. (do we care ?)
I have a doubt about the output not to be confusing if both time and planet/body parameters are passed as an array...
sorry if it looks like "are you crazy: everything have to be recoded for that" or "seriously... RTFM" or "go read the issue #00000" ... i tried my best.

**Comment by brandon-rhodes** [comment]
The question is at least not crazy — there have been other questions about whether, for example, positions on Earth could become an array so that many locations could have things computed at once.

My first two thoughts are:

1. From an API perspective, I'm not sure this would work out, because there would be no way for users to guess whether the result, given N times and M planets, would be an N×M array or an M×N array.
2. Which of the calculations could be cached to make this faster for two planets — if you could list the values that are getting computed twice, we can investigate how to avoid recomputing them, and see if we can work out a fix independently of whether we wind up creating planet arrays!

**Comment by gyth** [comment]
1.  we are on the same page.
whoever I question myself about the following code that would increase the api "spaghettiness": the order of the "call" could define the order of the array result.
```python
positions = earth.at(jd).observe(multiplanet)  # NxM
positions = earth.observe(multiplanet).at(jd)  # MxN
```

about craziness and "spaghettiness" what to think about this:
```python
positions = observer(multiplace).at(multitime).observed(multiplanet)  # OxNxM
positions = at(multitime).observer(multiplace).observed(multiplanet)  # NxOxM
positions = observed(multiplanet).observer(multiplace).at(multitime)  # MxOxN
# and so on ...  
 ```
it is both pleasant to see and a bit scary! 

maybe simpler, but we loose the object oriented looking code
```python
positions = getpositionmatrix(origin = multiplace, at = multitime, target = multiplanet)
# by the order of the arguments we have the order of the array result
# any argument could be array or single value
# if origin omitted then it is solarsystembarycentric based
# optional: if time omitted then now() ?
 ```
at my level of programing (ground level)  what i see there is an array nightmare falling on me.
my question now:  is the versatility or some millisecond (if any)  worth it ? one fat big array is not always the best for optimizing algorithms memory or time wise; is it ?
 **where is the balance between flexible-versatile and confusing-bloated api  ?**


 2.  I am afraid, my understanding of your library or almanacs or celestial  inner mechanisms is not good enough for having a precise answer.
 I was thinking of the vector solarsystembarycenter -> observer (with some doubts  in the case of apparent observation: relativity stuff may prevent us to reuse the same vector ???)

**Comment by brandon-rhodes** [comment]
Allowing time to be an array is for efficiency — the operation of processing several times is strictly parallel, so it made sense to snatch some efficiency along that axis.

If you are thinking of the observer position calculation as being redundant across several `.at().observe()` calls, you're correct! But, happily, the API was designed to allow a way around it:

    earth = planets['earth']
    observer = earth.at(jd)

    for name in 'moon', 'sun':
        print observer.observe(multiplanet)

That way, the observer's position only gets computed once, instead of _n_ different times.

Maybe I should add a note about that to the documentation! Do you have an opinion of where it should go — where would you have found it the most easily? Otherwise I can try to choose a place for it myself, and we can see if other users run across the information or not!

**Comment by gyth** [comment]
well, i guess issue closed.
http://rhodesmill.org/skyfield/positions.html could be a good place for insert the information above ?

I have probably other questions on other part but i will calm my "inner troll" for now. 
at least i will try:)

thank you again with all my respect for this wonderful work of yours.

**Comment by brandon-rhodes** [comment]
Thanks for pointing out that the docs lacked this hint, I've just added it!
