### ISSUE TITLE
Skyfield module not found

### ISSUE THREAD

**Issue by tnatusch** [skyfielders/python-skyfield#159]
I have used pip to install skyfield on a Mac running OS X 10.9.5. The install appears to end successfully and I see a skyfield package in /Library/Python/2.7/site-packages, there are both __init__.py and __init__.pyc files in the skyfield package directory.

Attempts to import skyfield or skyfield.api from inside python fail. 

>>from skyfield.api import load or >> from skyfield import load for instance return "ImportError: No module named skyfield.api " / "ImportError: No module named skyfield " respectively.

This is almost certainly a newbie python programmer issue but any guidance would be appreciated.

**Comment by brandon-rhodes** [comment]
Which Python binary are you invoking? If you have several copies installed, you need to invoke the one that lists `/Library/Python/2.7/site-packages` when you run `import sys; print(sys.path)`.

**Comment by brandon-rhodes** [comment]
I'm going to close this for the moment, but feel free to re-open if you're able to return later with more information!

**Comment by codiau** [comment]
ModuleNotFoundError: No module named 'skyfield'

I was able to repeat this error, depending on which platform(Android phone or W10 Desktop),  I tried to run it on. The problem in my instance was that I tried to run it as root instead of as a normal user. That it!

So on a Ubuntu 20.04 distro running on a Windows 10 box as "Windows Subsystem for Linux system", no problem. On a ubuntu 18.04 distro for Android running on my Samsung S8 using "UserLAnd", it crokes with the error. One platform is forgiving, the other not.

Never run user level apps as root. It's insecure and can even be destructive and/or lead to confusing results as in my case. I know better which is why I found it quickly. Otherwise I would have been spinning my wheels for hours trying to figure it out.
