### ISSUE TITLE
extend subpoint() to off-nadir

### ISSUE THREAD

**Issue by craigim** [skyfielders/python-skyfield#195]
I believe I am trying to use Skyfield in the reverse of how it was intended and I am wondering if it can be done with existing functionality in a way that is non-obvious to me as a Python noob or if it is a candidate for a feature enhancement. 

Namely, I want to calculate when a particular spot on earth will be imaged by LandSat 8 or other Earth observing satellite. I can get a TLE set from space-track, and I can look up to see that the field of view for LandSat's imaging camera is ~15º. From the orbital propagation in Skyfield, I can get a position using `at()`, a heading vector using two closely-spaced positions, and the point on the Earth looking directly at nadir.

What I'd like to be able to do is to get the subpoint ±7.5° off-nadir in the plane that contains the nadir vector and is normal to the heading vector. Those endpoints define a scan-line. If I do the same thing 30 seconds later, I have a bounding box. I can then test to see if the bounding box intersects my ROI or contains my point (which I'm currently doing using GDAL). Rinse, repeat over some time of interest up to around 2 weeks post-epoch. I can currently do this to see if the ground track goes through an ROI, but if I'm interested in a satellite such as [Aqua or Terra](https://modis.gsfc.nasa.gov/about/) which has a 3000 km ground swath, the ground track could completely miss a bounding box around, say, Mt Rainier Nat'l Park, but still get a clear shot of the mountain.

**Comment by JoshPaterson** [comment]
Could you define the scan-line by creating a vector centered at the subpoint and parallel to the cross product of the position and velocity vectors?

**Comment by craigim** [comment]
Only if the Earth were flat. A scan line isn't really a line but a curved geodetic connecting the location where the each off-axis line-of-sight intersects the Earth (or other central body). A 3000km line covers quite a bit of arc on the Earth's surface

But if I could put optional angles into `subpoint()`, I could do a line, a box, or, with a nadir point and an off-nadir point, define the intersection of a cone.

The tricky part is deciding to do when the LOS vector does not intersect the central body. Functions I've written in MATLAB will return a lat, lon, altitude and an "offEarth" flag. For on Earth, altitude is 0 and offEarth is false. For off Earth, lat/lon/alt give the point of closest approach and offEarth is true.

**Comment by craigim** [comment]
The VIIRS imaging spectrometer on the NOAA-20 satellite has a scanning imager, which scans a track ~54° to either side. At its altitude of ~825km, that gives a 3000 km cross-track swath for each line in an image. The state of New Jersey is 112 km wide. That means that NOAA-20 could image the entire state in one pass, but the line traced by the subpoint would never intersect the polygon that defines the state's borders. If I want to predict when NOAA-20 will get a complete image of New Jersey, it is not enough to determine when the subpoint crosses the New Jersey shapefile polygon. I need to know when a line defined by the intersection of the line-of-sight at 54° off-nadir cross-track, 0° along track, and the Earth's surface at either side of the scan line intersect with the New Jersey shapefile polygon. Figure 21 at the very bottom of the page of the ESA's Earth Observing page for the Kompsat 3a satellite has a pretty good diagram of the geometry https://directory.eoportal.org/web/eoportal/satellite-missions/k/kompsat-3a (found via Google image search for "cross-track gsd satellite").

The way I ended up solving my problem is by using the free version of [System Tool Kit (STK) by AGI](https://www.agi.com/products/engineering-tools) which can solve this problem, but won't interface with other languages for automation without very costly licensed modules. It's the automation I'm after. If you wanted to visualize the kind of problem I want to solve, the Terra satellite, which carries the similar MODIS instrument, is in their built-in database, as is the shapefile for New Jersey. You can run an "access report" which will then give you the times for when the footprint of the imager intersects with New Jersey and will display it on a 2D or 3D map.

I will probably end up trying to hack something together using Skyfield for the satellite position prediction and then set up a separate set of vectors and a WGS84 Earth to calculate the intersection, though my Python skills are rather rudimentary. I was hoping that since much of the calculation is already being done internally in calculating the intersection of the nadir vector with the Earth that the same calculation could be done at a particular pair of angles with respect to the satellite's local body-centered ENU coordinates. I do realize, however, that as I said at the outset, I am using the library for the opposite of its intended purpose and that this may be beyond its scope.

**Comment by craigim** [comment]
For reference, I've used the formulas given in this [GIS Stack Exchange](http://gis.stackexchange.com/a/21128/62651) answer to get LOS intersections with Earth from an orbital position, but that was in MATLAB.

**Comment by brandon-rhodes** [comment]
> I was hoping that since much of the calculation is already being done internally in calculating the intersection of the nadir vector with the Earth that the same calculation could be done at a particular pair of angles with respect to the satellite's local body-centered ENU coordinates. I do realize, however, that as I said at the outset, I am using the library for the opposite of its intended purpose and that this may be beyond its scope.

Alas, `subpoint()` is much simpler than you're imagining — it is much less impressive than that. It isn't doing any vector intersections at all. It uses plain trig to generate the geocentric latitude, then uses that as a guess of what the geodetic latitude might be and iterates exactly three times on the error in the geodetic latitude to drive it to zero. You can see the code here:

https://github.com/skyfielders/python-skyfield/blob/99248a2ad8a8d5d88753cace5287378e515ff824/skyfield/earthlib.py#L58

It performs no vector intersections at all.

> Another good illustration is from the talk you linked. At 15:29, the satellite that imaged the yellow region captured most of the AOI in the white box, but the subpoint didn't get anywhere near it.

I agree that the subpoint is not useful to you. You are going to need to compute the entire bounding box of the area the satellite is looking at as a rectangle on the Earth's surface, and will then want to perform a polygon shape intersection of that area with the area you're interested in observing and measure how much of it overlaps.

There seem to be many libraries that could help you with the geometry, as lots of folks these days want to compute the intersections of shapes on the Earth's surface in Python; I see a library called Shapely mentioned a lot, though it seems to use Cartesian coordinates and thus only work well with small areas of the globe — a manual projection step is necessary before using it.

I wonder what the best Python library is for true spherical GIS work? I was recently looking at the JavaScript library for NASA's interactive Earth globe widget (it's like Google Earth but you're in control instead of Google), and it has many classes for dealing directly with polygons on the Earth's surface without the need to perform a projection first:

https://nasaworldwind.github.io/WebWorldWind/

I wonder if there's a similarly powerful library for Python?

**Comment by brandon-rhodes** [comment]
(Having clarified that the "subpoint" logic wasn't doing nearly what you thought it was, I'm going to close this for now, since a completely different solution will be needed (I think?) for your problem — but please feel free to re-open if you see a way to generalize "subpoint" that I haven't, or simply to keep making comments here to share ideas about how to solve your problem in other ways!)

**Comment by craigim** [comment]
@karatemir I ended up solving the problem using some vector math and it works pretty well.

Using subpoint(), one gets the point on the Earth surface at which the vector normal to the ellipsoid points directly to the spacecraft. Normalizing that vector and taking the negative of that vector gives the nadir pointing vector.

In my case, using the known FOV (in the example above, I know the swath is +/-26° from nadir), I rotate that nadir vector around the velocity direction by constructing a rotation matrix. Using the StackExchange link above, I then project those vectors down to the WGS84 ellipsoid. I do that for each time point and that gives me three lines: the ground track and the two swath limits. From there I can construct polygons using successive pairs of time points and calculate my intersections using shapely.

In your case, you would start with a set of vectors that define a nadir looking footprint (looks like it would be a cone). For each subpoint, rotate those by your squint and off-nadir angles (if those are fixed, do that once at the start), and then project them to the Earth. If your spot size isn't gigantic, you could chose only 3-4 points to project to and then fit those points to an ellipse under the assumption that the footprint is close enough to a plane. Your swath width is then the ellipse extrema.

**Comment by karatemir** [comment]
@craigim thanks for the explanation.

**Comment by gmorain** [comment]
Hi @craigim, the original topic of this issue is exactly the problem I want to solve, but for other satellites. Have you shared somewhere the code you wrote for your solution described below?

Thank you in advance!

> In my case, using the known FOV (in the example above, I know the swath is +/-26° from nadir), I rotate that nadir vector around the velocity direction by constructing a rotation matrix. Using the StackExchange link above, I then project those vectors down to the WGS84 ellipsoid. I do that for each time point and that gives me three lines: the ground track and the two swath limits. From there I can construct polygons using successive pairs of time points and calculate my intersections using shapely.
