### ISSUE TITLE
Travis CI: http://maia.usno.navy.mil/ser7/deltat.data requires a user-agent

### ISSUE THREAD

**Issue by cclauss** [skyfielders/python-skyfield#199]
IOError: cannot get http://maia.usno.navy.mil/ser7/deltat.data because <urlopen error [Errno 104] Connection reset by peer>

https://travis-ci.org/skyfielders/python-skyfield/jobs/421496309#L669

**Comment by brandon-rhodes** [comment]
I'm able to visit that URL — what IP range is your computer trying to fetch it from?

**Comment by cclauss** [comment]
This PR is related to accessing that URL from Travis CI.  In a browser on my local Mac, I was able to fetch from that URL consistently.

**Comment by brandon-rhodes** [comment]
I suppose I'll have to come up with another idea — I wonder if Travis CI supports static files yet? I guess I could also think about committing it to the repository for the sake of the integration tests.

**Comment by cclauss** [comment]
It just needed a __user-agent__.  Without the headers bit, requests.get() just hangs.

$ __python3__
```
>>> import requests
>>> url = "http://maia.usno.navy.mil/ser7/deltat.data"
>>> headers = {'user-agent': 'python-skyfield'}
>>> requests.get(url).text
```

**Comment by brandon-rhodes** [comment]
Could you double-check that code fragment? You are not using the `headers` when you make the request, so — at least the way it's written here — the behavior of `get()` should be exactly the same whether the `headers` line is there or not.

When I run the line, there's a pause of a second and then the file contents appear on the screen. (But that's local, of course, not from Travis.)

I'm going to see if I can commit a sample version of each file to the repo for the use of the Travis tests.

**Comment by cclauss** [comment]
Sorry, you are correct...  I have fixed to code above.

**Comment by brandon-rhodes** [comment]
Thanks! The code now changes the headers that the Navy gets, but I get the file back whether that user agent is set or not — I wonder why my IP address is given the file either way, while yours sees a difference based on user agent?

In any case, it's a great idea to break the Travis tests free of dependence on third-party I/O, so I have committed some sample timescale files to the repository:

https://github.com/skyfielders/python-skyfield/commit/0502c958be3936a78e6032ea2af46d772d0a6c6a

This might not solve the problem long-term because they'll go out of date, but for the moment Travis should hopefully go reliably green again. Thanks for noticing this systematic problem before I had a chance to sit down and parse the build output myself!
