### ISSUE TITLE
Dawn/Dusk

### ISSUE THREAD

**Issue by Bernmeister** [skyfielders/python-skyfield#225]
In the olden days of PyEphem, to calculate dawn/dusk, I used [this](https://stackoverflow.com/questions/2637293/calculating-dawn-and-sunset-times-using-pyephem) for inspiration.

For Skyfield, I have looked at the Topos object (both API and under a debugger) but I don't see a field for horizon (horizon should be set to say -6 degrees for civil twilight).

Is it possible to calculate dawn/dusk in Skyfield (and if so, how)?

**Comment by brandon-rhodes** [comment]
Twilight calculations would be a nice new feature, so I'll keep this issue open until there's a chance to add them. In the meantime, you could make your own copy of sunrise_sunset:

https://github.com/skyfielders/python-skyfield/blob/e83d751c0b80d2dbb14dcc0038c574ed2b43f69c/skyfield/almanac.py#L178

but instead of the value -0.8333, you would use an even deeper angle — here are the angles used by the Naval Observatory:

https://aa.usno.navy.mil/faq/docs/RST_defs.php#twilight

**Comment by SupahNoob** [comment]
@brandon-rhodes Would you consider it overkill to use your library in place of `astral` for this sort of thing? This issue is timely, as I found your work here while trying to dig up an old script that used `PyEphem`. Being able to pinpoint the phases of twilight is very interesting to me.

**Comment by brandon-rhodes** [comment]
I think that Skyfield times for twilight would more precisely agree with the official numbers from the USNO than would numbers from PyEphem, which might if you measured them be sometimes one minute different because of small differences in its estimation of where the Sun and Earth are. But my guess is that either library would be well within the precision you need, given that dusk and dawn never proceed exactly according to plan anyway because of humidity and air layers and clouds.

What precision does your application need? That's the first question.
