### ISSUE TITLE
Inconsistent results depending on how time is given

### ISSUE THREAD

**Issue by donalmur** [skyfielders/python-skyfield#233]

**Comment by donalmur** [comment]
HI 
I am getting some different results depending on how i give the time. I get the following results from the code below. 
The positions are different despite the same time.  The format of the output is also different so I wonder what is happening here. 


<Time tt=2454230.584030211>
<Time tt=2454230.584030211> [-5.98505489e+06  3.56143411e+06  3.76495333e+03]
2454230.584030211
[-5982855.34012479  3564887.25245819    33749.87687857]
<Time tt=2454230.584030211>
[-5982855.34012479  3564887.25245819    33749.87687857]
<Time tt=2454230.584030211>
[-5.98505489e+06  3.56143411e+06  3.76495333e+03]





import numpy as np
import sqlite3 as sqlite
import datetime as DT
import skyfield.sgp4lib as sgp4lib
import skyfield.api as sfapi
import matplotlib.pylab as plt
from  scipy.integrate import odeint
from nrlmsise_00_header import *
from nrlmsise_00 import *
from skyfield.units import AU_KM
from numpy.linalg import norm

ts=sfapi.load.timescale()
tle=('1 26702U 01007A   07130.08322947  .00001149  00000-0  10904-3 0  9993\r\n', '2 26702 097.7536 149.3388 0004800 135.9265 224.2305 14.95457491338501\r\n')
sfodin = sgp4lib.EarthSatellite(tle[0],tle[1])
print (sfodin.epoch)
t=sfodin.epoch
d=t.utc_datetime()
rv=sfodin.at(t)
print(t,rv.position.m)
t0=t.tt
secperday=24*60*60
tsolve=np.arange(0,1*secperday,5*60)  # one day in steps of 5 min
spgt=ts.tt_jd(tsolve/secperday+t0)
spgrv=sfodin.at(spgt)
print (t0)
print(spgrv.position.m[:,0])
print (spgt[0])
rv=sfodin.at(spgt[0])
print (rv.position.m)
print(t)
rv=sfodin.at(t)
print (rv.position.m)

**Comment by brandon-rhodes** [comment]
I have only had a few minutes to look at your issue as I catch up on various projects, but the difference, if you `print(t.__dict__)` and `print(t.ts.__dict__)` to look inside the time objects, is that the little time object created for the satellite's epoch is attached to a little pretend timescale object that doesn't really have any data files loaded. The only reason, if I recall, that I made the epoch a time object was so that folks could do math comparing it to other times, and print it out using the time formatting routines; I didn't think through what would happen if someone grabbed that date and tried doing a calculation with it.

I'll think about how we can help folks avoid trying to use the epoch date for calculations — maybe it should throw an exception instead of quietly working but with an invalid delta T value?

I'll assign this issue to myself so that I'm regularly reminded and keep thinking about the best approach. In the meantime, thanks again for letting me know!

**Comment by brandon-rhodes** [comment]
Skyfield now not only allows a timescale to be passed to new satellite objects, but also uses the default built-in timescale if none is provided, providing leap seconds at least up to the current date. So, happily, I think this poor behavior will disappear with the next release of Skyfield!
