### ISSUE TITLE
Issue connecting to navy.mil for deltat.data on 1.10

### ISSUE THREAD

**Issue by lexington1776** [skyfielders/python-skyfield#238]
Seeing issues with loading of timescale, specifically with this deltat.data file.  Is there a way to disable the use of this particular timescale?

`  File "/opt/conda/lib/python3.6/site-packages/skyfield/iokit.py", line 275, in timescale
    data = self('deltat.data')
  File "/opt/conda/lib/python3.6/site-packages/skyfield/iokit.py", line 185, in __call__
    download(url, path, self.verbose)
  File "/opt/conda/lib/python3.6/site-packages/skyfield/iokit.py", line 479, in download
    raise IOError('cannot get {0} because {1}'.format(url, e))
OSError: cannot get http://maia.usno.navy.mil/ser7/deltat.data because Remote end closed connection without response`

**Comment by lexington1776** [comment]
Thank you for the update.  That would be great if you could include a copy with the Skyfield library.  I'll keep an eye out for any new updates.

**Comment by mountain** [comment]
In China, we face connection problems.

**Comment by BrendanLeber** [comment]
Today in the USA I get the same error and navy.mil doesn't even resolve as a valid hostname.

**Comment by barrycarter** [comment]
I don't think `navy.mil` ever resolves, though it does have MX records. Try `www.navy.mil` instead.

I put an uptimerobot.com (not an endorsement) on http://maia.usno.navy.mil/ser7/ and it has a reasonable uptime of about 98% since I started monitoring on 22 Dec 2018.

Of course, mirroring is always a good idea (could we use google's cache or something maybe?)

**Comment by brandon-rhodes** [comment]
I have just released https://pypi.org/project/skyfield/1.11/ that supports `load.timescale(builtin=True)` that does not try to download updated files — enjoy!
