### ISSUE TITLE
consider pole coordinates (x,y) in EOP

### ISSUE THREAD

**Issue by lcx366** [skyfielders/python-skyfield#268]
Does this package consider the pole coordinates (x,y) in the EOP when involving conversions between GCRS and ITRS? It seems that only the length-of-day and leap seconds are considered.

**Comment by brandon-rhodes** [comment]
You are correct; the pole cooordinates have never yet been needed. Look for comments that look like `# TODO: wobble` to see the places where the code will go once a project member adds it (at least, those are the spots where I'm imagining the code will go). Do you have an application that now needs them? If so, could you share a sample of how you're currently doing the coordinate transform, and share the form in which you have the x and y available? We should be able to come up with a way to get the data connected to the transform you're doing!

**Comment by brandon-rhodes** [comment]
@lcx366 — I am going to temporarily close this issue pending more information from you. Please re-open it as soon as you are ready to share what Skyfield call you are making for your GCRS to ITRS conversion, and we can figure out how to get EOP coordinates added so that the extra bit of precision gets incorporated. Thanks!
