### ISSUE TITLE
ts.utc_datetime() downgrades to millisecond precision (while showing microseconds)

### ISSUE THREAD

**Issue by EirikrT** [skyfielders/python-skyfield#293]
A timescale can be built with microsecond precision using a datetime that has microseconds.  But when outputting via .utc_datetime(), the precision is only milliseconds (with 3 trailing zeros for microseconds).  However, the timescale object still has the full precision since it can output via .utc_iso(delimiter='T', places=6) and still show the full microseconds.

Ex:
t = ts.utc(datetime.datetime(2014, 12, 21, 16, 22, 42, 186479, tzinfo=pytz.utc)

t.utc_datetime() yields: 
2014-12-21 16:22:42.186000+00:00
(186479 microseconds is rounded to 186000 microseconds)

t.utc_iso(delimiter='T', places=6) yields:
2014-12-21T16:22:42.186482Z

My skyfield version is 1.12

**Comment by brandon-rhodes** [comment]
You will note that the final few digits are not exactly reproduced — "479" here changes to "482" — because microseconds are, alas, outside the range of a Julian date expressed as a 64-bit floating point number.

If I expand the code to save microseconds to the datetime object, then a time like "12:00" will become "12:00:00.000029" and almost never will users be able to convert to and from datetimes without seeing the error in the low-order digits. I think it was this consideration which motivated the rounding.

If I turn the precision all the way up to 6 digits, here, for example, are the 3 possible times that exist over the 100 microseconds following the one you specify above:
```
from skyfield import api

ts = api.load.timescale(builtin=True)
strings = set()
for i in range(100):
    t = ts.utc(2014, 12, 21, 16, 22, 42.186479 + 0.000001 * i)
    strings.add(str(t.utc_datetime()))

for string in sorted(strings):
    print(string)
```
Which prints:
```
2014-12-21 16:22:42.186482+00:00
2014-12-21 16:22:42.186522+00:00
2014-12-21 16:22:42.186563+00:00
```
So I could perhaps give 1 more digit of precision — the '"4" in the first number that turns into "5" in the second two — while still letting folks do round-trips of integral numbers of seconds without having noisy digits added to the end. But I don't think the user experience would be improved by exposing the final two digits?

I suppose I should at some point look into what Python eventually did with its own floating point display, when they stopped showing as many repeating decimals. I'm not an expert in that area, but could maybe learn how to squeeze another half-digit into the precision without ruining integral numbers of seconds.

**Comment by brandon-rhodes** [comment]
As you'll see from the commit above, the behavior is now documented, and a plan has been added to the project TODO to improve the situation once someone can devote time to researching approaches. Thanks for bringing this to my attention, I'm hopeful that no one else will be confused now that the effect is documented, and I'm hopefully we'll improve things in the future.

**Comment by brandon-rhodes** [comment]
Okay, time to really fix this, instead of just documenting the problem.
