### ISSUE TITLE
Why is almanac._find_maxima a protected function?

### ISSUE THREAD

**Issue by Deuchnord** [skyfielders/python-skyfield#300]
I'm writing a program in Python 3 that computes some useful information to prepare amateur astronomy observation nights, and want to compute the culmination time for the major objects of the Solar system. On a recomandation #243, I use the `almanac._find_maxima` function, which looks for a major part like `almanac.find_discrete`.

Since then, PyLint tells me that `_find_maxima` is a protected function because its name starts with an underscore. Is there any reason for it to not be public? Is there any other strategy I should use instead?

**Comment by brandon-rhodes** [comment]
I keep the underscore `_` in front of the name because the routine does not yet behave well. Very often an astronomical quantity is computed using values of very different magnitudes — like, say, the position of Paris relative to the center of the Earth (millions of meters) and the position of Jupiter (many trillions of meters). Typically some values that combine to make a result are increasing while others are decreasing. The problem is that they each do so at their own precision. This means that, if you look very closely at the resulting value, it has no one single maximum. Instead, it has lots of little tiny local maxima at the tips of its sawtooth wave, sawtooth because one value is moving smoothly in one direction while another of lower precision is taking bigger jumps.

Until I can work out how to make the routine behave well and not make every tooth of the sawtooth a maximum, I need to keep it in unofficial status lest unwary folks try using it and are surprised by its misbehavior.
