### ISSUE TITLE
On Calendars from East Asia

### ISSUE THREAD

**Issue by mountain** [skyfielders/python-skyfield#307]
There are many different systems of the the traditional China calendars, and the latest version is still in use in China, Korea and Vietnam. The latest version was released at the end of Ming dynasty hundreds years ago and in 2017 the calculation was standardized by Standardisation Administration of China. See https://en.wikipedia.org/wiki/Chinese_calendar

Interesting thing is a very long chronological records of astronomical events was keeped in Chinese history books, the officials at observatory recorded almost each Eclipse observable in that area, sun, moon and planet orbit on the sky and other rare events. These records could be a test set of our current astronomical knowledge.

Maybe the calculation is out of the current scope of skyfield package, but possibly here we may consider a good api to support tasks like that.

Just an idea and a small note.

**Comment by brandon-rhodes** [comment]
> Interesting thing is a very long chronological records of astronomical events was keeped in Chinese history books, the officials at observatory recorded almost each Eclipse observable in that area, sun, moon and planet orbit on the sky and other rare events. These records could be a test set of our current astronomical knowledge.

Yes, historical records from Asia have been helpful in several areas of science! An article I saw said that we were able to date a large earthquake in 1600 thanks to ancient Japanese tsunami records:

https://www.newyorker.com/magazine/2015/07/20/the-really-big-one

And Chinese records of eclipses have been of help to scientists working to understand the pace at which the Earth’s rotation is slowing. Look for the section on “China” in this article:

https://academic.oup.com/astrogeo/article/44/2/2.22/278981

They say they would be happy if historians would help them find more observations from the past, so if you know of good sources of Chinese records that they did not consider, they would be happy to know — at the end of the article they say: “more historical observations are needed. Reliable data would be particularly valuable in the most ancient period — before 700 BC — and also for a few centuries on either side of AD 500. The prospects of obtaining such observations are difficult to assess; the cooperation of historians would be much appreciated!”

> Maybe the calculation is out of the current scope of skyfield package, but possibly here we may consider a good api to support tasks like that.

Yes, world calendars are out of scope for Skyfield, which is interested in the behavior of the Solar System and objects beyond it. A library that modeled the whole Chinese calendar or other world calendars would need to be a separate Python project, both because it is not necessarily related directly to astronomical positions, and also because users might want to be able to load up the calendar functions without all the extra code in Skyfield to do Solar System positions and calculations.

If you find a Python library that does world calendars, or wind up creating one, I would be happy to link in the Skyfield documentation on “Time” to projects that could help Skyfield users convert between different calendars.

Do you know of any projects I should link? If so, then I could add them before closing this issue.

**Comment by brandon-rhodes** [comment]
I am going to close this issue for now since calendars would be their own big separate Python project, but feel free to add further comments if you know of existing calendar projects the Time page should link to. Thanks!
