### ISSUE TITLE
Canned list of cities

### ISSUE THREAD

**Issue by Bernmeister** [skyfielders/python-skyfield#316]
In PyEphem, the file cities.py contains a convenient list of cities, with name, latitude, longitude and elevation.   

Any chance this would magically appear in Skyfield please?  If not, I'm happy to swipe the PyEphem version and use that :-)

**Comment by brandon-rhodes** [comment]
Alas, no, I am not expecting to add a geographic database to Skyfield; a city list would not fit Skyfield's limited mission of being about astronomy. Just like Skyfield relies on NumPy and Pandas to do many computations, instead of doing everything itself like PyEphem used to, so I'm happy to let other Python libraries take care of the big and popular issue of giving coordinates for geographic locations.

Please do use PyEphem's list of cities if you find it convenient!
