### ISSUE TITLE
'ModuleNotFoundError' - No module named 'skyfield'

### ISSUE THREAD

**Issue by johnbest5673** [skyfielders/python-skyfield#322]
I have tried installing using pip, pip3 and pip3.7. Everytime I get the message that 'Successfully installed skyfield'. 

But when I run the sample program, I get the error. I am using Python 3.7 on Win7.

**Comment by brandon-rhodes** [comment]
I am not familiar with how Python is laid out on Windows, but those symptoms are common across all operating systems when there are multiple Pythons installed and `pip` is putting things one place but the `python3` you are running expects them to be somewhere else. Try searching the web for "python cannot find pip installed module", maybe with "windows" thrown in there too, and see if any of the Stack Overflow answers that come up help you figure out which paths your `pip` and `python3` are using.

**Comment by brandon-rhodes** [comment]
@johnbest5673 — Were you able to work out whether Skyfield was really getting installed, and if so why Python was having trouble finding it? I'm going to close this issue for now, as it's been quiet for 20 days, but feel free to re-open if you do determine that the problem is from something about the way Skyfield is packaged. Thanks!
