### ISSUE TITLE
How to create positions from alt-az?

### ISSUE THREAD

**Issue by ozntyr** [skyfielders/python-skyfield#349]
I'm want to create temporary positions from alt-az values and calculate its new values some time later. From what I can see on https://rhodesmill.org/skyfield/positions.html I can only create with ICRF. I've tried from_altaz() but it returns Apparent ICRF and I cant at(t) an apparent or radec().at(t) to get new altaz values.  So is there a way to calculate this or should I create my own functions to do it?

```
observer = earth + Topos('40.10 N', '29.07 E')

t = ts.now()
direction = observer .at(t).from_altaz(alt_degrees=50, az_degrees=180)

ra, dec, distance = direction.radec()
```

**Comment by brandon-rhodes** [comment]
Your script gives:
```
Traceback (most recent call last):
  File "tmp38.py", line 1, in <module>
    observer = earth + Topos('40.10 N', '29.07 E')
NameError: name 'earth' is not defined
```
Could you provide a script that does not result in an error? Thanks!

**Comment by ozntyr** [comment]
here it is
```
from skyfield.api import load, Topos, Star
from skyfield.data import hipparcos

planets = load('de421.bsp')
earth= planets['earth']
observer = earth + Topos('40.10 N', '29.07 E')

ts = load.timescale()
t = ts.now()
direction = observer .at(t).from_altaz(alt_degrees=50, az_degrees=180)

ra, dec, distance = direction.radec()
```

**Comment by brandon-rhodes** [comment]
Thanks so much! This is much more complete. On the one hand, I get:
```
Traceback (most recent call last):
  File "tmp38.py", line 3, in <module>
    import time.sleep
ModuleNotFoundError: No module named 'time.sleep'; 'time' is not a package
```
— but on the other hand, I think I can now figure out how to fix the broken script. I'll take a look at it!

**Comment by ozntyr** [comment]
by the way I'm running this code on a raspberry pi

**Comment by brandon-rhodes** [comment]
So. At the moment there is no official support for that kind of calculation, because it is difficult to do confidently without knowing the distance to the object; refraction as the light goes past a planet could change the apparent position, for example, and Skyfield currently has no reverse-correction for refraction to undo the effect of light passing possibly several planets on the way into the Solar System.

But if you wanted to ignore those effects and get a slightly lower-precision result, I think you could:

```
from skyfield.api import load, Topos, Star

planets = load('de421.bsp')
earth= planets['earth']
observer = earth + Topos('40.10 N', '29.07 E')

ts = load.timescale()
t1 = ts.utc(2020, 3, 21, 19, 10)
t2 = ts.utc(2020, 3, 21, 19, 14)  # 4 minutes ~= 1 degree of sky rotation

direction = observer.at(t1).from_altaz(alt_degrees=50, az_degrees=180)
ra, dec, distance = direction.radec()

from skyfield.api import Star
approximate_pos = Star(ra, dec)
alt, az, distance = observer.at(t2).observe(approximate_pos).apparent().altaz()

print(alt, az)  # should be about one degree away in azimuth
```

This produces:

```
49deg 59' 14.5" 181deg 33' 13.5"
```

1. I have given up `now()` in favor of hard-coded times. I always find this preferable in sample scripts, since it makes the output stable now matter how far in the future someone tries running the script.
2. It's possible if I thought a little harder that there would be a way to go directly from the vectors inside of `direction` to an Earth-relative position that had the same vectors but at a later time. If we decide this is a use case that should be added to the documentation, I'll try to make that pivot to avoid the round-trip through spherical RA and dec angles.
3. So: if I'm understanding, you're considering an object that unlike most objects, does not move between time `t1` and `t2` but stays fixed in the sky? Is your goal to keep, say, a telescope pointed at the same point in the sky given an initial altaz, or is your problem a bit different?

**Comment by ozntyr** [comment]
> So: if I'm understanding, you're considering an object that unlike most objects, does not move between time t1 and t2 but stays fixed in the sky? Is your goal to keep, say, a telescope pointed at the same point in the sky given an initial altaz, or is your problem a bit different?

Yes, exactly. I'm trying to design some kind of control mechanism for my dobsonian and I thought it would be nice to be able to set a frame to watch and it might help taking long exposure photos. It wasn't my main goal for this project but I thought it would be a nice feature. Thanks for the help I didn't try your example code yet but it looks like it'll work for what I need. I didn't know I could create new star with just ra-dec.
You are right using hard coded times is nice for asking questions like this but in the real world applications you mostly will use your so I just copy-pasted  my test codes without thinking :D
Thank you again for the help
