### ISSUE TITLE
Finding current angle between earth and other planet

### ISSUE THREAD

**Issue by skynoob-new** [skyfielders/python-skyfield#359]
Its been a while since i used `skyfield`, earlier i tried to get `oppositions and conjunctions`  using the link [https://rhodesmill.org/skyfield/almanac.html#opposition-and-conjunction](url), is there a way to find the current angle between `2 planets` or even better would be to get results for `custom angles` along with `opposition and conjunction` which is usually `0` or `180`.

**Comment by brandon-rhodes** [comment]
Yes, there's a `separation_from()` method on any position. Where in the documentation could I more prominently place it so that it's easier for users to find? Which sections of the documentation were you drawn to as you were interested in the current angle? If you'll let me know where you were naturally drawn to look, I can go put a mention there of the method.

Adding a new custom-angles routine is interesting, I'll look into it. For the moment, you should be able to just cut-and-paste the existing almanac routine and make one of your own with your own angles; hopefully that will get your project moving again! What angular separation are you searching for?

**Comment by techiesoft** [comment]
> Which sections of the documentation were you drawn to as you were interested in the current angle?

Not sure which section was that, but when i was just going through `opposition and conjunction` i sort of start thinking about it.

in `alamanac.py` i saw the below line
```
return ((slon.radians - tlon.radians) / pi % 2.0).astype('int8')
```
I am not a math/Astronomy geek like you, so i dont really know what the above line does, but is it for retrieving the `180 degree` ? if that is the case, what would be the formula for getting the `90` or `45` or whatever. My question might be completely stupid, please bear with me

**Comment by brandon-rhodes** [comment]
```
return ((slon.radians - tlon.radians) / pi % 2.0).astype('int8')
```

Yes, that's a step function that returns 0 for an angle less than 180° and 1 for an angle greater than that.

Building a routine that detects an angle like 45° will work a bit differently since that's not a clean multiple of pi, and involves a design question: are you interested in when the two objects are separated by 45° either way, or only when one object is ahead of the other and that's the separation?

**Comment by techiesoft** [comment]
i am yet to explore `separation_from()` so i am not sure about it.  I saw this link [https://rhodesmill.org/skyfield/api-position.html#skyfield.positionlib.ICRF.separation_from](url) and in the example it deals with `ICRF`. Does this function works only with `ICRF`

**Comment by brandon-rhodes** [comment]
Yes, it works for `ICRF` positions. That's the kind you are using, I believe?

What larger problem are you trying to solve by looking for those angles? There might be an approach I can recommend using other tools in Skyfield if I had more context.

**Comment by techiesoft** [comment]
For any time and date, i want to know the angle of  any `planet`  from `earth`

**Comment by brandon-rhodes** [comment]
With respect to an observer stationed where in the Solar System?

**Comment by techiesoft** [comment]
You are right, yes.

**Comment by brandon-rhodes** [comment]
I was asking a question. I will rephrase it: “From what vantage point in the Solar System do you want to measure an angle?” An angle is always measured between two lines, so we need somewhere from which we can draw both a line to the Earth and another line to the other planet. Otherwise there would be no angle to measure.

**Comment by techiesoft** [comment]
oops, sorry, its like `opposition` and `conjunction` i.e  
```
    earth_at = ephemeris['earth'].at
    sun = ephemeris['sun']
```

**Comment by brandon-rhodes** [comment]
Besides looking at the main almanac file, you might also want to look at:

https://github.com/skyfielders/python-skyfield/blob/master/skyfield/almanac_east_asia.py

It looks not simply for conjunctions and oppositions, but for any moment that the Sun→Earth→Planet angle is a multiple of 15°. So I think that 45° differences would show up whenever its finder reports the number `2`.

**Comment by techiesoft** [comment]
That function does not have any `target` planet or am i missing something

**Comment by brandon-rhodes** [comment]
You are correct. I was merely using its math as an example of how to look for angles besides 180° — you would definitely want to use that math in your own copy of the routine. My guess is that you should start with a date on which you know that the planets were aligned in the way that interests you, and then compute angles on that date until you figure out how to get Skyfield to print 45° for that date, and then wrap that in an almanac function for searching.

Can you create a small Skyfield program that prints out the angle you are interested in? That would be a good start, and would make it clearer exactly which angle you are asking about. I have not yet been able to tell from your descriptions what kind of angle you want?

**Comment by techiesoft** [comment]
i think i have not conveyed my question clearly, sorry, the `opposition and conjunction` gave me an impression that the `ecliptic longitudes` are angles, in that case, i need `45 degree` ecliptic longitudes. Sorry if my question is wrong.

**Comment by brandon-rhodes** [comment]
Yes, it is certainly true that an ecliptic longitude is an angle! But a given planet will have a different ecliptic longitude depending on where in the Solar System you are viewing the planet from. From the Sun's point of view, Jupiter has a different ecliptic longitude at this moment than Jupiter does from the Earth, for example.

From your interest in conjunctions, it sounded like you are interested in the longitudes that an observer here on earth would see, in our own sky.

But when you said “For any time and date, i want to know the angle of any planet from earth”, I had difficulty. If you mean "the angle in the sky between where I see the Earth shining and where I see the planet shining", then there must be some other place in the Solar System that you are measuring longitudes from, since only if you are somewhere else is the Earth visible in the sky. If instead you are describing an Earth-based observation, then I am not sure what other object besides the planet itself you would use for the other "arm" of the angle.

It might be clearer if you described what you are trying to accomplish with 45°, or else: could you give a date on which the angle you are interested in was at 45° for a particular planet? That might make it clearer which angle you mean.

**Comment by techiesoft** [comment]
Ok, here is 180 degree 
![180](https://user-images.githubusercontent.com/58113774/79655504-33c5c080-81d0-11ea-8ca7-f9284dbebce5.png)
and i want to know what is the current degree of this or can this be taken as `45°`?
![this](https://user-images.githubusercontent.com/58113774/79655802-493aea80-81d0-11ea-8c60-97a1f485c00c.png)

**Comment by brandon-rhodes** [comment]
Interesting! So you want to know whether an observer positioned at the Sun, if they measured the position of Earth and the position of Mars, would see them at 45° apart — or, maybe, see their ecliptic longitude as 45° apart, ignoring their little elevation above or below the ecliptic?

You are correct that nothing in the almanac module does that; all almanac routines are for traditional observations from the point of view of the Earth. This idea of an angle from the sun will need to be written from scratch.

I'll think through whether there's some way that Skyfield can support a computation so general, without making the programmer understand the math part of creating a function that detects the angles.

In the meantime: I think that the description of `separation()` was confusing; thank you for pointing out that it had little relevance to normal Skyfield users. I have rewritten its example:

https://rhodesmill.org/skyfield/api-position.html#skyfield.positionlib.ICRF.separation_from

Hopefully that makes clearer how `separation()` would be used in normal code!

**Comment by techiesoft** [comment]
> Interesting! So you want to know whether an observer positioned at the Sun, if they measured the position of Earth and the position of Mars, would see them at 45° apart — or, maybe, see their ecliptic longitude as 45° apart, ignoring their little elevation above or below the ecliptic?You are correct that nothing in the almanac module does that; all almanac routines are for traditional observations from the point of view of the Earth. This idea of an angle from the sun will need to be written from scratch.

Do you  mean we already have something that does this if observer is positioned at earth and measure the position of `Sun` and `Mars` and give us the angle?

> In the meantime: I think that the description of separation() was confusing; thank you for pointing out that it had little relevance to normal Skyfield users. I have rewritten its example:

>https://rhodesmill.org/skyfield/api-position.html#skyfield.positionlib.ICRF.separation_from

>Hopefully that makes clearer how separation() would be used in normal code!
Yes the doc looks clear now.

**Comment by brandon-rhodes** [comment]
> Do you mean we already have something that does this if observer is positioned at earth and measure the position of Sun and Mars and give us the angle?

Yes, that is what `slon.radians - tlon.radians` does in the code we discussed earlier — it gives the difference in the ecliptic longitudes of the Sun and a planet as viewed from Earth.

**Comment by barrycarter** [comment]
I might be misunderstanding here completely, but I think 
this might be a request for a generic geometric event 
finder like CSPICE has: 
 
https://naif.jpl.nasa.gov/pub/naif/toolkit_docs/C/cspice/gfevnt_c.html 
 
described as "Determine time intervals when a specified 
geometric quantity satisfies a specified mathematical 
condition."   
 
My guess is there are other Python libraries to solve 
this problem and that you might even be using them to 
implement some of Skyfield's other functions. 
 
Not sure if you want to add a "here's how to 'goalseek' 
with skyfield" section to the documentation and/or 
implement a skyfield-specific version of a generic Python 
goalseek function

**Comment by brandon-rhodes** [comment]
@barrycarter — The routines in `skyfield.searchlib`, which power the almanac examples, are intended to be Skyfield’s generic goal-seeking algorithms. It’s likely that, yes, there should be a new chapter of the manual exploring how to use them.

**Comment by brandon-rhodes** [comment]
@skynoob-new — I thought I should check and ask: did our recent work over on the other issue, in which I wrote some new docs illustrating the event finder, also address this issue, or is there some additional work that needs to be done until your 45° question is also answered?

**Comment by skynoob-new** [comment]
i am yet to work on this, since i am new to all of these, struggling a bit, may be we can close this for now and i will re open when i need it?

**Comment by brandon-rhodes** [comment]
That sounds like a good idea! Feel free to post further comments here, either with or without re-opening the issue, and I can answer questions about the behavior of your code once you’ve put some together. Good luck!
