### ISSUE TITLE
Incorrect intldesg for earth satellites

### ISSUE THREAD

**Issue by bobbyfrasier** [skyfielders/python-skyfield#360]
Hi,

I think I found an issue for the satellites with a intldesg having as a format "YYLLLPP"
For exemple, while the ISS has as intldesg "98067A", the satellite FUNCUBE-1 officialy has "13066AE" (more than 26 satellites where launched together).

When loading the TLE file, the satellites created by skyfield only get the first letter and therefore many different satellites have the same intldesg (13066A in my example).

**Comment by brandon-rhodes** [comment]
Thanks for pointing that out, I see the same problem when I try loading that satellite! I'll have to release a new version of "sgp4", the library Skyfield uses for satellites, since the bug is in the new C++ accelerated version that was added recently.

I'll close this once I have it released!

**Comment by brandon-rhodes** [comment]
I've just released sgp4 2.6 which hopefully resolves this issue — feel free to make further comments here on this issue if after installing it you still see the issue. And thanks again for letting me know!

**Comment by bobbyfrasier** [comment]
It seems to work ! Thanks

**Comment by bobbyfrasier** [comment]
Wait, there is a new issue due to your modification I think !
If the intldesg has 6 characters, like the ISS, the sgp4 library seem to take the space right after and save if in the intldesg, so it is now "98067A " instead of "98067A".
You should check if the last character is a space and take it out of the string, I think !

**Comment by brandon-rhodes** [comment]
The official C++ library that I am now using, when it's able to compile, leaves the spaces in. Actually, it both leaves them in and changes them to underscores! So the value would really be `98067A_`. I decided to switch it back to spaces so it looks more like it does in the TLE file, though.

Since the official SGP4 always makes it 7 characters, I decided to do the same, so that indexes that work in other languages will work in Python too.

I plan to update the docs to make the structure of the string clearer, just as soon as I adjust the Python version to match so that they stop working differently.

**Comment by brandon-rhodes** [comment]
Having given it two more days of thought, I have repented. Even though it will make the Python a little less exactly compatible with the underlying C++, I'm going to trim trailing whitespace from the `intldesg`. The new `sgp4` release making the tweak should go out this afternoon.
