### ISSUE TITLE
Skyfield far slower than ephem

### ISSUE THREAD

**Issue by Sec42** [skyfielders/python-skyfield#389]
I wrote a small script to match sightings with satellites via their TLE.

The script using skyfield is about 80x slower than the same using ephem.

My question is: can this be improved? Am I using skyfield wrong here?

```
#!/usr/bin/python3
import sys
import datetime
from skyfield.api import load, utc, Topos

satlist = load.tle_file(sys.argv[1])
ts = load.timescale(builtin=True)


tim=float(sys.argv[2])/1000.
lat=float(sys.argv[3])
lon=float(sys.argv[4])
alt=int(sys.argv[5])*1000

time_t = datetime.datetime.utcfromtimestamp(tim)
time_t = time_t.replace(tzinfo=utc)
t = ts.utc(time_t)
mysat=Topos(latitude_degrees=lat, longitude_degrees=lon, elevation_m=alt)
my=mysat.at(t)

minsep=9e9
sname=None
for sat in satlist:
    pos=sat.at(t)

    sep=pos.separation_from(my).degrees
    if sep<minsep:
        sname=sat.name
        minsep=sep

print("Minimum: %4.2f: %s"%(minsep/1000,sname))
```
 
vs. similar code with ephem:

```
#!/usr/bin/python3
import sys
import math
import datetime
import ephem

degrees_per_radian = 180.0 / math.pi

satlist = loadTLE(sys.argv[1])

tim=float(sys.argv[2])/1000.
lat=float(sys.argv[3])
lon=float(sys.argv[4])

t = datetime.datetime.utcfromtimestamp(tim)

minsep=9e9
sname=None
for sat in satlist:
    sat.compute(t)

    sep=ephem.separation((sat.sublong,sat.sublat),(lon/degrees_per_radian,lat/degrees_per_radian))*degrees_per_radian
    if sep<minsep:
        sname=sat.name
        minsep=sep

print("Minimum: %4.2f: %s"%(minsep,sname))
```

As a datapoint: using a TLE file with 75 satellites, and running in a 1000x loop, I get runtimes of 0.17s for ephem vs. 14s for skyfield.

Is a way to optimize/speed up what I'm doing with skyfield?

Thanks,
   Sec

**Comment by brandon-rhodes** [comment]
Yes, alas, saving 0.8 seconds — which is normally noticeable — is in this case not a substantial improvement!

So, let me at least quickly answer your original question:

1. No, you are not using Skyfield wrong! Your code looks like how I'd also initially try solving the problem with Skyfield.
2. Yes, I suspect that there are substantial speedups available here, both within Skyfield and also some changes we can make to how your script is written to try taking advantage of the fact that Skyfield supports NumPy vectors.

I now have both scripts set up and running on my system — thanks for providing nearly complete scripts for me to try out!

(I did have to write a `loadTLE()` myself, but it only took a minute. The only other snag was that the output didn't agree — but then I saw `minsep/1000` which puts the output of that script in different units. Just because I'm curious: what was the motivation behind the difference?)

At a first reading, some of the difference derives from the fact that Skyfield builds real Python objects with metadata, which, alas, takes more time than returning raw numbers. Whereas the ephem routine `ephem.separation()` has no idea where you are getting those numbers from, and no way to check whether they're meaningful or are in the same reference frame, and no way to know if you have the units correct (great job, by the way, getting all those units manually coerced, without any help from PyEphem!), Skyfield is building Python objects that know their coordinate system and know their common origin and thus don't require you to supply any units or perform and conversions when you run `.separation_from()`. All those objects and checks make Skyfield far friendlier for users — I never get questions any more whose answer is "those are radians, not degrees"! — but they also take time.

But they shouldn't take *that* much longer, right?

I am going to spend some time profiling the Skyfield code and see what we can do about its speed in this particular use case, which is one I've not gotten the chance to optimize for: normally folks run a single satellite against *n* times instead of all satellites against a single time!

Then I'll also dig in to whether the script could be written a bit differently to get better speed.

Give me a couple of days to fit this in amongst some other work (assuming I don't get other interruptions), and we'll see if we can get things improved!

It's possible that Skyfield, even if we make your script faster, won't ever be as fast as PyEphem here. Raw C code that provides no frame of reference and no unit conversions, but spits out raw floats that you then pass to the next C-language routine as raw floats, is probably going to remain at least a bit faster than Skyfield code — at least using its official API that builds meaningful objects.

But we'll see how things look after we optimize a bit!

**Comment by Sec42** [comment]
Hi,

first: thank you for taking the time to look into it. second: sorry about omitting the loadTLE.
Reason for the minsep difference is basically a paste-error. One of the reasons I was originally rewriting the ephem code in skyfield because i wanted to replace separation with distance as a measure for the "best match". So I had `sep=(pos-my).distance().m` in the skyfield variant, and then printed /1000. to get km. -- I swapped that back to separation to see if that was the cause of the slowness (which it wasn't) and then kept it, so my report was less complicated.

Sorry for any confusion I created. I have about 150k sat "sightings" from the course of one day, that I quickly wanted to match to the ~76 active satellites which is why i noticed the slowdown compare to the ephem-based code.

I did a quick look with cProfile - but I don't think I understand it (and the skyfield internals) properly enough to gain insights. It seemed that a lot of time was spent in .at() which is why I thought your explanation about precision sounded very plausible. 

Thanks,
   Sec

**Comment by brandon-rhodes** [comment]
Ah, yes, if separation had been in meters the /1000 makes quite a bit of sense!

I have managed one speedup already by noticing how slow the default NumPy cross product implementation is. If you:
```
pip install https://github.com/skyfielders/python-skyfield/archive/master.zip
```
— and try your script again you might see a few percent difference in Skyfield's speed. (If instead it's slower, or gives wrong answers, let me know!)

But the bigger problem seems to be that Skyfield returns full velocity vectors, which PyEphem makes no attempt to generate. I wish there were a way to write Python where a function that returns, say, 2 results position and velocity, if you called it like `r, _ = f()` to throw away the velocity, would skip the statements in `f()` that only contribute to the second return value. Then one could quite naturally compute and return several interrelated results, knowing the user would only pay for the ones they needed to use.

So I will probably try out adding a flag to the Earth satellite `.at()` where the caller can pass something like `skip_velocity=True` if they want to avoid computing a velocity vector they don’t plan to use.

It would make Skyfield faster for such cases, but it will probably still be noticeably slower than PyEphem. I'll try one or two more tweaks and see how close we can get, though! I don’t like having too big a performance difference yawning between the two implementations.

**Comment by brandon-rhodes** [comment]
@Sec42 — I have shaved the computation time down a bit more, but it’s still more than an order of magnitude slower than PyEphem. The main reasons appear to be:

1. Skyfield keeps up with satellite velocity, not just position, doubling the number of certain coordinate transforms.
2. Skyfield keeps up with distance, not just 2-dimensional spherical coordinates, so the question of separation gets computed using vectors (making it more robust, but also slower).
3. Skyfield for simplicity uses a single reference frame which is not, alas, that of the rotating Earth, but of the fixed quasars.

Here is a quick approach that sidesteps several of the above problems. In addition, it uses the underlying `sgp4` library's ability to, in a single Python command, compute the positions of `n` satellites over `m` times. It might run without error if placed at the bottom of your script:

```
def find_closest_satellite(t, satlist):
    a = SatrecArray([sat.model for sat in satlist])
    jd = np.array([t._utc_float()])
    e, r, v = a.sgp4(jd, jd * 0.0)

    r = r[:,0,:]  # eliminate t axis since we only have one time
    v = v[:,0,:]
    r = r.T       # move x,y,z to top level like Skyfield expects
    v = v.T

    ut1 = np.array([t.ut1])
    r, v = TEME_to_ITRF(ut1, r, v)

    r2 = mysat.itrf_xyz().km
    r2.shape = 3, 1  # add extra dimension to stand in for time

    sep = angle_between(r, r2)

    i = np.argmin(sep)
    closest_satellite = satlist[i]
    closest_angle = sep[i] / tau * 360.0

    return closest_satellite, closest_angle
```

By staying in the rotating ITRF frame, it saves several steps, and also takes advantage of Skyfield’s strengths by handling the whole list of positions as an array instead of slowly looping over them one by one.

But, still, it's not as fast as the PyEphem solution.

I'll continue to look at this as I have time, but my guess is that progress will come slowly. How might a computation like the above, for example, be wrapped up for easy end-user use? How could NumPy array operations for a single coordinate ever be as fast as PyEphem's simple move of returning raw floats and taking raw floats as arguments?

Feel free to keep this issue open, and I'll provide updates over the months if I find more edges of the computation that can be whittled away!

**Comment by glangford** [comment]
> I wish there were a way to write Python where a function that returns, say, 2 results position and velocity, if you called it like r, _ = f() to throw away the velocity, would skip the statements in f() that only contribute to the second return value. Then one could quite naturally compute and return several interrelated results, knowing the user would only pay for the ones they needed to use.

@brandon-rhodes I don't know the underlying code, and whether this idea is appropriate for something like velocity. But your wish/thought here reminds me of computed properties (using the @property decorator) - so that values are only calculated when they are needed. Could this be useful in some cases - eg. could velocity be deferred in the same way as CalcAttr here?
https://stackoverflow.com/questions/33991071/pythonic-class-instance-attribute-calculated-from-other-attributes

**Comment by brandon-rhodes** [comment]
That's an interesting idea! Skyfield does include some values that are computed on-demand, particularly on the Time object:

https://github.com/skyfielders/python-skyfield/blob/c10e7401598342c891d7befca00fc209392114e1/skyfield/timelib.py#L583

I’ll ponder whether velocity could become an on-demand property. One problem is that in some cases intermediate results that could be useful to its computation might be gone by the time it is accessed, whereas if it’s computed at the same time as position, the same matrices can be applied immediately to both. It can also be disconcerting for users if they think of, say, `.at()` or `.apparent()` as the "expensive step" where a calculation takes place, but if really it's the `.velocity` access at the end of the method chain which suddenly launches the intermediate steps that would have taken place to compute it. Also, it means that the final object with the `.velocity` property needs to keep a reference to every previous object — even if normally they would have disappeared and had their memory freed — until such time as it’s asked for the property value, so memory usage and object lifetime can be mysteriously higher.

My guess is that a more sustainable approach will be a `skip_velocity` option in `.at()` methods, that then results in methods like `.apparent()` from even needing to transform velocity because it would be a `None` object.

**Comment by Sec42** [comment]
Hi,

I got around to do a quick test with your snippet above: CPUtime is improved to 8x the ephem solution which is a nice improvement. Runtime of the test case is at around 3x the ephem solution due to sgp4 using multiple cores :)

Plugging in the function in my real code, I get 25.2s for ephem and 50.8s for the new code. That brings it back into usable territory for me.

Ohe thing, though is that the results seem to differ slightly. Interestingly it seems that the skyfield code has more mis-matches than the ephem version. This may be just unlucky, but I will investigate this a bit more & report later.

Incidentally this is one of the reasons I looked into skyfield: I wanted to use absolute distance instead of angle, because the "mis-matching" satellites are all at a different altitude. Am I correct that replacing
`sep = angle_between(r, r2)`
with
`sep = length_of(r-r2)`
should do the trick for that?

**Comment by brandon-rhodes** [comment]
Thank you for trying out the new code and sharing the new timing! I will share additional speedups if I find them, but am happy that at least some speedup has been achieved.

Yes, using `length_of()` between two positions should return the 3D length of the shortest line between them!

**Comment by glangford** [comment]
@brandon-rhodes Thank you for the pointer to timelib.py showing the use of `@reify`. I have a new level of appreciation for the work that goes into converting coordinates!

**Comment by glangford** [comment]
@Sec42 Can you share the first 50 lines or so of your profiler function call output?

One inefficiency I see in sgp4lib.py seems to be that `theta_GMST1982()` will be called repeatedly with the same value of `t` (the julian day), redoing the math to produce the same `theta` and `theta_dot` when `at()` is called.

I don't know how significant this is to overall performance, it is likely to be dominated by other factors. In my application it is not critical but I thought I would mention it in case it applied here.

**Comment by brandon-rhodes** [comment]
> theta_GMST1982() will be called repeatedly …

Yes, that's indeed true, and we could avoid that call by stashing the value somewhere, maybe on the `Time` object. I even did a quick experiment to do so during that recent performance work, but:

1. It made little difference to the overall time; it was a surprisingly small contribution to the cost of a small program computing positions.
2. The cost will go away if instead Skyfield adds full-fledged support for arrays of satellites, because the time would only get computed once for a whole array; so the extra code and complexity would use up RAM for most users but without necessarily having a benefit.
3. I have just removed a few cached values of time that were taking up memory, and wanted to think for a few weeks before adding a new one back.
4. I want to centralize Skyfield's half-hearted support for polar motion, which will affect the `TEME_to_ITRF()` routine. In particular, it will raise the question of what we cache: the theta angle itself, which would make us compute the matrices over and over again? Or would we cache the matrices, at 9× the RAM cost?

All of which has led to my holding off on caching that time unit for now. But it's not impossible to imagine that in the near future that some kind of caching could take place in case a `Time` is used on several satellites; but as it will be a small gain, I would rather take our time with the design.

**Comment by brandon-rhodes** [comment]
I am going to close this issue for now, as the “far slower” description in the title seems now to have been mitigated to at least one user’s satisfaction. But I will always continue to look for improvements to be made in Skyfield’s code and will be happy to see issues and pull requests related to specific routines that users have profiled and identified as bottlenecks in their computations.

Thanks again for the original question — the next release of Skyfield will be faster as a result!
