### ISSUE TITLE
Declination on Celestial Sphere appears to be wobbling.

### ISSUE THREAD

**Issue by ecomber** [skyfielders/python-skyfield#399]
I have been playing with the example in:

https://rhodesmill.org/skyfield/examples.html#what-is-the-right-ascension-and-declination-of-a-point-in-the-sky

And what I believe I am doing is taking a location on Earth (latitude_degrees=50, longitude_degrees= 0, elevation_m=0.0) and a view at a point on the Celestial Sphere from that location (alt_degrees=45, az_degrees=180) and plotting out the RA and Declination of that point. It runs every 5 minutes on a cron job.

The RA increases as expected, but while I explicated the Declination to be constant it follows a Sinusoidal graph with period of 24 hours (Min at 2020-06-29 06:30:01, Max at 2020-06-28 18:30:01 from 5 minute intervals) and the difference is 0.2243 Degrees, 13.4637 Minutes of arc.

I am at loss to explain this, any suggestions? On the face of it it appears that the Earth's Lat/Liong and the Celestial Sphere co-ordinates are not co-axial.

![Decl](https://user-images.githubusercontent.com/29634789/86012402-d216a380-ba15-11ea-8462-33cc34966e98.png)

Code is:
```
import time
from skyfield import api
from skyfield.positionlib import position_of_radec
ts = api.load.timescale(builtin=True)
timeNow = ts.now()
myTopocentricLocation = api.Topos(latitude_degrees=50, longitude_degrees= 0, elevation_m=0.0)
myselfNow = myTopocentricLocation.at(timeNow)
pos = myselfNow.from_altaz(alt_degrees=45, az_degrees=180)
ra, dec, distance = pos.radec()
print('{0},{1},{2},{3}'.format(time.time(), ra._degrees, dec.degrees, distance))
```

**Comment by brandon-rhodes** [comment]
> On the face of it it appears that the Earth's Lat/Liong and the Celestial Sphere co-ordinates are not co-axial.

You are correct, they are not co-axial. You should find them very very close to co-axial on January 1 of the year 2000 and less axial both before and afterward due to the facts that (a) the Earth's pole precesses over thousands of years, and (b) we set up our current celestial coordinate system based on the angle of the Earth's axis at the beginning of the year 2000; hence the name "J2000" for that system.

You can find out more here:

https://en.wikipedia.org/wiki/Axial_precession

(Am closing the issue, but feel free to comment further.)
