### ISSUE TITLE
utc_strftime(format) fails when format contains %f for fractional seconds

### ISSUE THREAD

**Issue by davetyp** [skyfielders/python-skyfield#421]
Where t is a time object,

this works:
`t.utc_strftime('%Y-%m-%d at %H:%M:%S UTC')`

but this fails:
`t.utc_strftime('%Y-%m-%d at %H:%M:%S.%f UTC')` 
with a traceback of "ValueError: Invalid format string."

**Comment by brandon-rhodes** [comment]
The underlying Python `strftime()` does not support `%f`, it doesn’t look like:

https://docs.python.org/2/library/time.html#time.strftime

And, drat, the link I provide for documentation is to a web site talking about an entirely different routine: the `datetime.strftime()` method, which Skyfield can’t use because on many Python versions a `datetime` cannot represent a leap second.

Could you call `utc_datetime()` and then call the `strftime()` method of each of the values returned?

**Comment by brandon-rhodes** [comment]
And, if you get the chance, check out the diff that I just committed, linked above — it tries to fix the errors in my documentation, and also tries to make the docs more convenient by going ahead and listing the most common formats.

**Comment by davetyp** [comment]
The diff makes it clear, no milliseconds format available. 

I tried calling `uct_datetime()` as you suggested and then parsing the result.  That's definitely a useful workaround, thanks!
