### ISSUE TITLE
Angles should be comparable/sortable

### ISSUE THREAD

**Issue by amandasaurus** [skyfielders/python-skyfield#426]
```python
Python 3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from skyfield.units import Angle
>>> Angle(degrees=10) > Angle(degrees=5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: '>' not supported between instances of 'Angle' and 'Angle'
```

This should return `True` correct? Or is there some weird `Angle` logic that makes that not possible?  Skyfiel 1.26 installed with `pip3`

**Comment by glangford** [comment]
```
Python 3.7.8 (v3.7.8:4b47a5b6ba, Jun 27 2020, 04:47:50) 
>>> Angle(degrees=10) > Angle(degrees=5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: '>' not supported between instances of 'Angle' and 'Angle'
>>> Angle(degrees=10).degrees > Angle(degrees=5).degrees
True
```

**Comment by brandon-rhodes** [comment]
If you ask each object for its `.degrees` (or its `.radians`, of course), those are NumPy arrays that share the full range of Python math operator methods, and `>` should work just fine.

To upgrade the Angle to do all the same operations that the NumPy arrays can do would mean writing something close to 30 new methods, that would each have to (a) make sure the other object is an angle too, then (b) turn around and call the NumPy array methods of the same name. Here's a list of some of the methods that would need to be added:

https://docs.python.org/3/reference/datamodel.html#emulating-numeric-types

It feels simpler just to have folks do math using real NumPy arrays instead? Is there somewhere in the documentation that I could describe the `.degrees` maneuver that would have helped you find it and try it out?

I suppose that instead of implementing all ~30 methods I could implement a `__getattr__()` that looked for a method of the same name on the NumPy array `.radians` and, if it existed, returned a wrapper around that method that verified that the other argument was also an Angle and then called it with that angle’s `.radians`. 

1. It would have to be a bit intelligent about the return value. Subtraction, for example, should return another Angle, but `>` would return a simple NumPy arrays of bools that shouldn't be interpreted as an Angle. Maybe just checking the return array's dtype would successfully make that distinction, though.
2. I would probably need to maintain a whitelist of safe-to-wrap dunders, so that other random attributes of the NumPy array did not shine though as though they belonged to the Angle.
3. It would be slower in all cases than someone just pulling off the `.degrees` of each angle and using them. I am wary of conveniences that tempt people away from the simplest possible approach that’s also faster.
4. There would now be Two Ways of Doing Somthing™, which is generally not considered Pythonic.

And yet.

And yet, I am tempted, because Python would let it be done fairly simply and elegantly, in a way that would be impossible in most other languages.

I very often later regret doing things whose impetus was “oooh, this would use a cool dynamic feature of Python!” So maybe I should decide against it. But I'll leave this open for a day, at least to see what I think of the idea when I come back tomorrow.

(And thanks, @glangford, for jumping in with the answer the user needed quickly, while I wrote much more than I was expecting about the problem!)

**Comment by glangford** [comment]
@brandon-rhodes There is a shortcut to writing all of the different methods (haven't tried it myself, just sharing an article discussing the problem). My approach is to just use `.degrees`. But if you are tempted to go further -

>To make classes comparable, you only need to implement` __lt__` and decorate the class with `functools.total_ordering`. This provides the rest of the comparison operators so you don't have to write any of them yourself.

Comparable classes in Python 3
https://stackoverflow.com/questions/6907323/comparable-classes-in-python-3

**Comment by brandon-rhodes** [comment]
Wow, I had not heard of that before — thanks for mentioning it!

Alas, because some Skyfield users are still on Python 2.6, it won’t be an option near-term. But it does suggest that some kind of wrapper might work here, and I could peek at how it’s implemented for ideas.

**Comment by glangford** [comment]
@rory If sorting a set of `Angle` objects was the goal,

```
>>> x = [Angle(degrees=10), Angle(degrees=1), Angle(degrees=5)]
>>> x.sort(key=lambda a:a.degrees)
>>> x
[<Angle 01deg 00' 00.0">, <Angle 05deg 00' 00.0">, <Angle 10deg 00' 00.0">]
>>> 
```
https://stackoverflow.com/questions/403421/how-to-sort-a-list-of-objects-based-on-an-attribute-of-the-objects

**Comment by glangford** [comment]
If Version 3 specifics are needed in future, we could check the `version_info` tuple:
```
import sys
if (sys.version_info > (3, 0)):
     # Python 3 code in this block    
else:
     # Python 2 code
```

**Comment by brandon-rhodes** [comment]
It turns out that `__getattr__()` does not get the chance to intercept calls like `__lt__()` to its class, because the `<` logic does a fast direct check first for whether the class has a `__lt__()` method — which bypasses the get-attribute logic entirely.

So without a simple mechanism for providing this feature, I am going to at the moment maintain the recommendation that users use one of the angle measures like `.degrees` or `.radians` to run NumPy routines like comparisons. It will be faster in any case; much simpler for the implementation; and, Skyfield won't fall out of date as the NumPy arrays gain more and more abilities and the `Angle` has to keep up to support them all.

@rory — Where in the documentation would it be most helpful to describe the `.degrees` approach? Let me know if there’s a specific place you looked before opening the issue. I’m thinking it belongs at the top of “API Reference — Units”.

**Comment by brandon-rhodes** [comment]
As this has been idle for more than a year, I'm going to hope that users are getting along fine by comparing or sorting degrees or radians as appropriate. I'll be happy to hear more ideas or problems here on the issue, though, so feel free to comment in the future despite its being closed. Thanks!
