### ISSUE TITLE
Getting ValueError: Failed to converge when loading comet list from Minor Planet Center

### ISSUE THREAD

**Issue by Bernmeister** [skyfielders/python-skyfield#430]
Following on from #428, using the ```master.zip``` from [here](https://github.com/skyfielders/python-skyfield/issues/428#issuecomment-670940243), running the code:

```
#!/usr/bin/env python3

import datetime, io, skyfield.api, skyfield.constants, skyfield.data.mpc

print( "Skyfield:", skyfield.__version__ )
latitude = -33
longitude = 151
now = datetime.datetime.strptime( "2020-08-08", "%Y-%m-%d" )
data = "    CK15A020  2015 08  1.8353  5.341055  1.000000  208.8369  258.5042  109.1696            10.5  4.0  C/2015 A2 (PANSTARRS)                                    MPC 93587"
timeScale = skyfield.api.load.timescale( builtin = True )
topos = skyfield.api.Topos( latitude_degrees = latitude, longitude_degrees = longitude )
ephemeris = skyfield.api.load( "de421.bsp" )
sun = ephemeris[ "sun" ]
earth = ephemeris[ "earth" ]
with io.BytesIO( data.encode() ) as f:
    dataframe = skyfield.data.mpc.load_comets_dataframe( f ).set_index( "designation", drop = False )
    body = sun + skyfield.data.mpc.comet_orbit( dataframe.loc[ "C/2015 A2 (PANSTARRS)" ], timeScale, skyfield.constants.GM_SUN_Pitjeva_2005_km3_s2 )
```

yields the following:

```
/usr/local/lib/python3.6/dist-packages/skyfield/data/mpc.py:207: RuntimeWarning: divide by zero encountered in double_scalars
  a = row.perihelion_distance_au / (1.0 - e)
/usr/local/lib/python3.6/dist-packages/skyfield/data/mpc.py:208: RuntimeWarning: invalid value encountered in double_scalars
  p = a * (1.0 - e*e)
/usr/local/lib/python3.6/dist-packages/skyfield/keplerlib.py:242: RuntimeWarning: invalid value encountered in double_scalars
  dE = dM/(1 - e*cos(E))
Traceback (most recent call last):
  File "magnitudeTest.py", line 17, in <module>
    body = sun + skyfield.data.mpc.comet_orbit( dataframe.loc[ "C/2015 A2 (PANSTARRS)" ], timeScale, skyfield.constants.GM_SUN_Pitjeva_2005_km3_s2 )
  File "/usr/local/lib/python3.6/dist-packages/skyfield/data/mpc.py", line 222, in comet_orbit
    row['designation'],
  File "/usr/local/lib/python3.6/dist-packages/skyfield/keplerlib.py", line 156, in _from_mean_anomaly
    E = eccentric_anomaly(eccentricity, M)
  File "/usr/local/lib/python3.6/dist-packages/skyfield/keplerlib.py", line 247, in eccentric_anomaly
    raise ValueError('Failed to converge')
ValueError: Failed to converge
```

**Comment by brandon-rhodes** [comment]
Wow, a perfectly parabolic orbit! I've never seen one of those before.

I was able to fix that first error, but then saw several more — it looks like the contributor who wrote the Kepler library did not anticipate a perfect parabola, a point at which all the equations and series become unstable. There are alternative formulae to handle such a case:

https://en.wikipedia.org/wiki/Parabolic_trajectory#Barker's_equation

@JoshPaterson — any interest in getting them implemented? If not then we can put the task on my backlog of things to do.

**Comment by JoshPaterson** [comment]
I will be able to work on this later tonight!

**Comment by brandon-rhodes** [comment]
@JoshPaterson — Neat, I'm glad you're available so quickly! Feel free to use whichever issue, this or the other one, you find more convenient; I'm watching them both.

**Comment by JoshPaterson** [comment]
PR #431 makes the above example code run without errors for me, but I still need to write some tests to confirm that it produces correct results. @Bernmeister: could you try that PR and see if the numbers it produces are plausible? Thanks!

**Comment by Bernmeister** [comment]
@JoshPaterson Thanks and testing now...I'm noticing differences in magnitude values compared to PyEphem (for both comets and minor planets).  Also I've hit another exception when calculating some minor planets...I'll sort this out and determine if another ticket should be opened.

**Comment by brandon-rhodes** [comment]
I have just landed 4685183bbc6290d0ab9044baf586472e8800942b which simplifies a bit how comet orbits are built, so that the anomaly quantities do not appear at all in the formulae — which is possible since `CometEls.txt` always gives the orbit as of the moment of (possibly fictitious and back-dated) perihelion, instead of having a non-perihelion epoch for which a nonzero *M* then has to be provided.

Through the commit, Skyfield now has a working test for a comet whose eccentricity is 1.0 — exactly the one you used here, @Bernmeister — and so that use case should now always work from now on.

I am a bit mystified that all comets were working and agreeing with PyEphem, because for the e=1.0 case I had to replace:
```
        p = row.perihelion_distance_au / 2
```
— with what I think is the actual relationship:
```
        p = row.perihelion_distance_au * 2.0
```
But maybe no e=1.0 comets were among your dataset? It was only by correcting that formula that the result agreed exactly with the Minor Planet Center.

@JoshPaterson — This now breaks comets free of all code linking the various anomaly values, unless I've missed a link that still exists somewhere. It will now be solely in the realm of minor planets that we can write tests that verify whether anomaly conversions work correctly in the cases e<1.0, e=1.0, and e>1.0. Let me know if that makes sense given your reading of the code as well. Thanks!

**Comment by Bernmeister** [comment]
@brandon-rhodes I poorly chose my words, so apologies.  What I should have written is that I ran the test code (above at the top of the ticket) using the changes made against the same original data and no exception.  I then ran my own application using the full MPC data and compared the rise/set/az/alt for a handful of comets from that data between PyEphem and Skyfield and the values all matched.  Sorry, my application reads in the full MPC data, but does a cull based on magnitude and only then do I "process" the remaining (handful) of comets.

**Comment by brandon-rhodes** [comment]
> Sorry, my application reads in the full MPC data, but does a cull based on magnitude and only then do I "process" the remaining (handful) of comets.

Ah! So unless an e=1.0 comet happened to be in your brightest comets list, that case would not have wound up as part of the experiment. That makes perfect sense. Thanks for clarifying!

Now that comets do no convergence at all, I am going to tentatively close this issue. If either one of you sees anything still amiss with comets, please re-open, but otherwise I think we can move on to the question of minor planets, and continue discussion over on #432.
