### ISSUE TITLE
Why is the Hipparcos Catalog treated differently to the planets data source at the API level?

### ISSUE THREAD

**Issue by Bernmeister** [skyfielders/python-skyfield#435]
To load a planets data source:

```ephemerisPlanets = load( "planets.bsp" )```

whereas for stars:

```
with load.open( "stars.dat.gz" ) as f:
    ephemerisStars = hipparcos.load_dataframe( f )
```

(for me, both sources are stripped down, local file versions of the originals)

Diving into ```skyfield/iokit.py``` under ```self.openers``` there is support for various file types.  For example, if loading a ```*.bsp```, the specifics are handed off to ```skyfield/jpllib.py```.  Although I did notice the comment about _old-faishoned_ (not sure if that is a euphemism for _deprecated_), I am wondering why stars are not handled in the same way.  Would make loading them more consistent with say planets.

**Comment by brandon-rhodes** [comment]
The auto-“load()” mechanism only works if a file format has a unique extension, by which Skyfield can guess what kind of content it contains.

1. Unfortunately the Hipparcos catalog lacks this — `.dat` is simply a generic old extension meaning “data” of any kind.
2. The catalog is loaded using Pandas, which not everyone has access to, so there would need to be some awkward auto-import behavior. Which would be doable, but having folks do the import themselves is far cleaner (because, for instance, type introspection tools can support the import more clearly than if it happened deep in a routine).

I have not, in fact, found any subsequent data import format with as clearly defined and unique an extension as `.bsp` so I am not clear whether any future data source will be able to support `load()`.

**Comment by Bernmeister** [comment]
@brandon-rhodes Thanks for the explanation.
