### ISSUE TITLE
Accessing latitude/longitude from Topos

### ISSUE THREAD

**Issue by Bernmeister** [skyfielders/python-skyfield#448]
In version ```1.26``` I was able to sneakily obtain the latitude/longitude from a ```Topos```:

```
topos = Topos( latitude_degrees = latitude, longitude_degrees = longitude, elevation_m = elevation )
observer = ( load( "planets.bsp" )[ "EARTH" ] + topos )
latitude, longitude = getLatitudeLongitude( observer )
```

from

```
def getLatitudeLongitude( observer ):
    for thing in observer.positives:
        if isinstance( thing, Topos ):
            latitude = thing.latitude.radians
            longitude = thing.longitude.radians
            break

    return latitude, longitude
```

But that broke in ```1.27```:

```AttributeError: 'VectorSum' object has no attribute 'positives'```

So I amended the function:

```
def getLatitudeLongitude( observer ): return observer.target.latitude.radians, observer.target.longitude.radians
```

How future-proof is this...or to put it another way, can you please provide a function to extract latitude/longitude from a ```Topos```?

**Comment by brandon-rhodes** [comment]
In general, only features described in the documentation are future-proof.

Despite that policy, I really ought to have put underscores in front of `positives` to make it `_positives`, to signal also in the code itself that the `VectorSum` was subject to change; I suppose that since `VectorSum` isn’t even documented I felt falsely safe. I believe I am being more consistent about putting underscores in front of internals than in more recent years (for example, in front of Kepler orbit objects); apologies for having forgotten to do that in the case of the old vector sum internals.

The switch to `.target` being the Topos itself is public and permanent; it was deliberate that I put no underscore in front of it. I think it makes eminent sense to keep the whole object around, and as we see in this example code, it makes it far easier to reach back from a position to information about its observer’s orientation.

But, of course, given Skyfield’s promise to document public APIs that are stable, I should add to the documentation somewhere a promise that the `.target` will be the `Topos` itself. I’ll do that before closing this issue!

**Comment by brandon-rhodes** [comment]
The availability of `.target` is now documented officially:

https://rhodesmill.org/skyfield/positions.html#position-attributes

So it can always be used in the future to learn the geographic coordinates of the center or target.
