### ISSUE TITLE
AttributeError: 'Timescale' object has no attribute 'from_datetime'

### ISSUE THREAD

**Issue by shahgazer** [skyfielders/python-skyfield#459]
Hello,

I keep getting this error, 

_**AttributeError: 'Timescale' object has no attribute 'from_datetime'**_

even after copy pasting the exact code from the first example [here](https://rhodesmill.org/skyfield/examples.html) and the topic "UTC and your timezone" [here](https://rhodesmill.org/skyfield/time.html) 

I noticed that the attribute "from_datetime" is not listed from the timescale object when I inspected using vscode. 

Any tips? 

Thanks
Shah

**Comment by brandon-rhodes** [comment]
What version of Skyfield are you using?

**Comment by brandon-rhodes** [comment]
Since this issue has gone 3 weeks without activity, I'm going to tentatively close it, hoping that the problem was that you were using an old Skyfield version and fixed your script by upgrading. But if the issue wound up being deeper or more difficult to resolve, simply re-open, describing what you discovered. Thanks!
