### ISSUE TITLE
Anonymous ftp access will officially be discontinued at CDDIS

### ISSUE THREAD

**Issue by sheridansmall** [skyfielders/python-skyfield#464]
From https://cddis.nasa.gov/ 

> On 31 October 2020, anonymous ftp access will officially be discontinued at CDDIS. Beginning October 1, 2020, CDDIS will bandwidth limit ALL IPs using anonymous ftp to just 50KB/s and will limit simultaneous downloads to only 3 per IP address. CDDIS is STRONGLY recommending all users begin to transition to using alternate method of access to the CDDIS archive. Examples of alternate methods can be found at: https://cddis.nasa.gov/Data_and_Derived_Products/CDDIS_Archive_Access.html. 

Skyfield uses anonymous ftp access to resources on cddis.nasa.gov in several places in its code-base and will need updating

**Comment by brandon-rhodes** [comment]
Thanks for sharing! Happily, Skyfield recently turned off download-by-default. Work is currently underway to transition Skyfield to IERS for the data that in `builtin=False` mode is currently pulled from the CDDIS FTP site.

Possibly, though, I should go ahead and push out a quick Skyfield version that switches these URLs, to stop the clock on this breakage. I'll consider a 2.11.1 release and report back!

**Comment by brandon-rhodes** [comment]
@sheridansmall — Thanks again for alerting me to the fact the server is shutting down!

Instead of waiting to finish an overhall of UT1 that I currently have underway, I have gone ahead and released Skyfield 1.31 this morning so that at least folks can start pulling UT1 data from the IERS instead of the old CDDIS site. Let me know if you have any problems with the new code — hopefully it will not cause significant disruption for any users, but if the service shuts down in a week, then users are at risk either way. Fingers crossed.
