### ISSUE TITLE
FTP for _CDISS files is down

### ISSUE THREAD

**Issue by adelman** [skyfielders/python-skyfield#471]
This effects `deltat.data` and `deltat.preds`, and possibly others. The URL is references here: https://github.com/skyfielders/python-skyfield/blob/1.31/skyfield/iokit.py#L61 and seems to have been down since November 1st, 2020.

**Comment by nathan-leolabs** [comment]
Per https://cddis.nasa.gov/ :

" US Government security requirements no longer permit CDDIS to offer data via traditional unencrypted anonumous ftp; this service was discontinued on October 31, 2020. All data are still available, however access must be via HTTPS or ftp-ssl.

Instructions with examples and our FAQ can be found at: https://cddis.nasa.gov/Data_and_Derived_Products/CDDIS_Archive_Access.html "

**Comment by brandon-rhodes** [comment]
Yes — unhappily, NASA decided to no longer support anonymous FTP to that server and it was shut down October 30. The Skyfield CHANGELOG describes the service that has been switched to instead:

https://rhodesmill.org/skyfield/installation.html#october-24

Could you try the new version and see whether it works?

You can also keep using your current Skyfield version and select `builtin=True` in your timescales; since the files were no longer updated in any case, you wouldn't have been getting data any more recent than the copies built-in to Skyfield.

Let me know if either approach works for you!

**Comment by adelman** [comment]
We upgraded to `1.31`, and it's smooth sailing so far. Thanks for your help!

**Comment by brandon-rhodes** [comment]
Wonderful! I'm glad it's working again for you. Thanks for following up.
