### ISSUE TITLE
Failure to load timescale with builtin=False

### ISSUE THREAD

**Issue by bradsease** [skyfielders/python-skyfield#477]
Trying to follow along with the example [here](https://rhodesmill.org/skyfield/time.html#ut1-and-downloading-iers-data) to manually update the IERS file and `load.timescale(builtin=False)` appears to fail without attempting to download the file:
```
Python 3.9.0 (default, Nov 15 2020, 14:28:56) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from skyfield.api import load
>>> ts = load.timescale(builtin=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/brad/anaconda3/envs/test/lib/python3.9/site-packages/skyfield/iokit.py", line 354, in timescale
    with self.open('finals2000A.all') as f:
  File "/home/brad/anaconda3/envs/test/lib/python3.9/site-packages/skyfield/iokit.py", line 312, in open
    return open(path, mode)
FileNotFoundError: [Errno 2] No such file or directory: './finals2000A.all'
```
Based on the documentation, I expected this:
```
>>> ts = load.timescale(builtin=False)
[#################################] 100% finals2000A.all
```
A regular call to `load.timescale()` works normally.

Versions I've reproduced this error on:
- Python 3.8.5, 3.9.0
- skyfield 1.31, 1.32

**Comment by me-at-git-hub** [comment]
Same here, for the last 3 days.  
Other files I have tried are loading fine, with progress bars with verbose=True

de422.bsp
jup310.bsp
de421.bsp
de430t.bsp

They are being stored in a custom location properly after creating a custom Loader with that path.  I can provide that small script if that would further help.

load.days_old(filename) is working fine.

If this helps:

skyfield v 1.31 pip3 installed 3 days ago on an up to date Buster system on Pi 4B 4g

```pi@raspberrypi:~ $ python3
Python 3.7.3 (default, Jul 25 2020, 13:03:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import skyfield
>>> from skyfield.api import load
>>> from skyfield.api import Loader
>>> print(Loader.build_url('finals2000A.all'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: build_url() missing 1 required positional argument: 'filename'
>>> print(Loader.build_url(finals2000A.all))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'finals2000A' is not defined
>>> 
```

Other than the attempt to download finals2000A.all, I have just begun exploring skyfield, without any other problems encountered so far, but my experience with it is literally only days.  Many thanks for your efforts, and support!  Yes, I'm finally migrating from pyephem, only to be more up to date.

**Comment by brandon-rhodes** [comment]
@bradsease — I have just released Skyfield 1.33 with an attempted fix for this issue. If it doesn't fix it for you, simply re-open and we'll work further on it. Thanks for letting me know; since Skyfield's CI test suite is designed not to impose load on external web sites, this is the one case (downloading real files) that currently has to be tested by hand, and evidently I failed to test this case by hand correctly.

**Comment by brandon-rhodes** [comment]
Great! Thanks for quickly notifying me; hopefully other users get to avoid the error.

**Comment by me-at-git-hub** [comment]
Yes, it now works, but an odd thing that perhaps is worth noting...

Previously the following worked, where `./skyfield_keep`  was where I stored the files using a custom built loader, aiming it there.  In other words, the load.days_old() had no problem if I specified a complete path/filename, when the custom loader already had been told that full path.

```
print('days old = ', load.days_old('./skyfield_keep/de421.bsp'))
```
Yes, that worked in v 1.31

Now, the loader, ie, the custom built loader that has been given full path to the files already, now remembers that path, so that only the filename need be entered in the load.days_old(), and if one now specifies explicitly the full path/filename in the load.days_old(), when the custom loader is already now remembering it, it gets ... confused, giving the obligatory string of exceptions.  If that is how it should have worked before, then I will fix my earlier scripts and no longer explicitly give the full path/filename in load.days_old()  if I have already specified a path in a custom loader.  Is that correct?

And of course, thank you for such a quick fix and release!

**Comment by brandon-rhodes** [comment]
@me-at-git-hub — The `days_old()` routine has, alas, not changed between 1.31 and the current version 1.33; I just double-checked, and the only change to `iokit.py` at all is in how timescales are built. And I think their behavior has always been the same? To answer your questions:

1. Relative paths given to `days_old()` are relative to the Loader's base directory, given when it's instantiated.
2. Absolute paths given to `days_old()` can be anywhere on the filesystem.
3. The `days_old()` routine works on backup files and alternate files.

Could you provide an example of the exception you're seeing? That might help narrow down the problem.

**Comment by me-at-git-hub** [comment]
surely.

```
pi@raspberrypi:~/projects $ python3 skyfield_final2000A_all_tests.py
load and/or update skyfield reference files... 


Traceback (most recent call last):
  File "skyfield_final2000A_all_tests.py", line 95, in <module>
    main()
  File "skyfield_final2000A_all_tests.py", line 90, in main
    initialize_skyfield()
  File "skyfield_final2000A_all_tests.py", line 51, in initialize_skyfield
    print('days old = ', load.days_old('./skyfield_keep/de421.bsp'))
  File "/home/pi/.local/lib/python3.7/site-packages/skyfield/iokit.py", line 154, in days_old
    mtime = os.stat(self.path_to(filename)).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: './skyfield_keep/./skyfield_keep/de421.bsp'
pi@raspberrypi:~/projects $
```

By that last line, it looks like it is building the path to the file by adding the explicit full path/filename to the path I had already specified in the custom built loader in addition to the path/filename in the `load.days_old()`.  This problem did not occur in version 1.31, with the exact same script, now quite modified and not tracked with version software.  But I think I could duplicate it again tomorrow if you need to see the code.

**Comment by brandon-rhodes** [comment]
Could you do a quick downgrade to 1.31 (I think `pip install skyfield==1.31` might do it?) and share the same exception? Comparing line numbers between the two exceptions, one for 1.33 and one for 1.31, will help me track down the difference between the files. Thanks!

**Comment by me-at-git-hub** [comment]
There were no exceptions when running 1.31, except with trying to download `finals2000A.all` with **builtin=False**, which is now working in 1.33.   I can rev up a venv with 1.31 some time tomorrow.  It might not be until evening... sorry 'bout that.  Long day today.  About all I can do now is put my ear to the ground and let the slow whooshing of our young earth's molten iron core spin with the help of the metonic cycle.

**Comment by brandon-rhodes** [comment]
No problem with the delay! I'll watch for further comments here whenever you get the chance to circle back.

“There I lay staring upward, while the stars wheeled over, and each day was as long as a life-age of the earth. Faint to my ears came the gathered rumour of all lands: the springing and the dying, the song and the weeping, and the slow everlasting groan of overburdened stone.”

**Comment by me-at-git-hub** [comment]
"...my name is growing all the time, and I've lived a very long, long time; so my name is like a story. Real names tell you the story of things they belong to in my language, in the Old Entish as you might say. It is a lovely language, but it takes a very long time saying anything in it, because we do not say anything in it, unless it is worth taking a long time to say, and to listen to.”

Treebeard is clearly incompatible with twitter. 

Tomorrow then, hopefully.

**Comment by me-at-git-hub** [comment]
Got it!  

Sorry for the delay in circling back.

Nearly 100% confident there is nothing you need do, concerning what I thought might be a secondary issue.  It was me.  When I made a 'custom' instance of Loader, and assigned a custom path in it, it was then that an explicit path/filename passed into the .days_old() method of that custom instance will not aim at a path lower (closer to the file system volume mount point itself) than what was assigned in the custom loader.  It's world starts at the assigned custom path and further into any of its subdirectories, and it is blind to anything lower than that (back towards the volume mount point itself), or so my tests have borne out.  Also, because a baseline path is assigned in the custom loader, consequently '.' and './' are no longer understood in an explicit path passed into `.days_old()`.  It can no longer make any sense of '.' or './', and so triggers the exception(s). 


When one names a new instance of custom loader with the name `load`,  that sure makes tracking it down a little more thoughtful, since the new instantiation becomes the effective `load`, even if one did a `from skyfield.api import load`, and previously that first imported load could 'see' all around the file system universe.  After the new instantiation, with the same name of `load`, that first imported load is no longer what is being called by `load.days_old()` or any other method of `load`.  The new instance, that was also named `load` at the instantiation, is now what rules the day, at least in the scope of that function.  My bad.  

What with the `finals2000A.all` issue at the same time, and a few other skyfield tests, I was juggling too many chainsaws at the same time.  After making more instances, with different names, and testing what `.days_old()' could and could not see through those various instances, the fog cleared.  If you intended a different behaviour of custom loaders, please let me know.  We could then open a separate issue and go into more detail.  Apologies about the now recognizably unnecessary tangent.

Thank you again for fixing `finals2000A.all`.

**Comment by brandon-rhodes** [comment]
I'm glad that you worked out what was going on! Hopefully you will at least find the Loader's behavior predictable from this point on, even if you have to use `../` to get to outer directories once your `load()` routine is pointed at a subdirectory. Thanks for following up!

**Comment by me-at-git-hub** [comment]
Just tried that.  Though I am embarassed for not having tried that sooner, it is a good type of _embarassed_.  It worked of course!
 
Thank you for your generosity toward someone with far far less experience than yourself.
