### ISSUE TITLE
Rectangular (cartesian) and horizontal coordinates true of date

### ISSUE THREAD

**Issue by dataadvisor** [skyfielders/python-skyfield#480]
Good morning, Brandon

As the *```epoch=date```* argument already implemented for spherical **equatorial** and **ecliptical** coordinates of an object, how can we have the **rectangular (cartesian)** and **horizontal coordinates** for the **epoch of date**?

Please be noted, not barycentric.

non of the **```apparent()```** for rectangular coordinates and **```altaz()```** for horizontal functions can get the **```epoch=date```** argument.

One solution can be adding **```epoch=date```** to the **```apparent()```** function as the main, then all **apparent** coordinates can have **```True of Date```** result too.

Best,

**Comment by brandon-rhodes** [comment]
Yes, it should be possible to support the production of cartesian vectors in the epoch-of-date coordinate system. Because it might help us come up with a good method name: what’s an application in which they might be useful?

There is not, however, any concept of “of-date” for altaz() because neither altitude nor azimuth are referenced to the intersection of the ecliptic and the equator (which is the intersection that slowly wheels across the sky and makes the whole of-date idea necessary). They are referenced to an observer’s real-world horizon and therefore always an “of-date” coordinate system.

**Comment by dataadvisor** [comment]
One of the applications, for example, would be 3D plotting in the epoch of date.

I am afraid I disagree with you on altitude and azimuth. In the Skyfield, also we are computing horizontal coordinates from the apparent coordinates, which they affect by epoch. Please see the attachments, which show the different values for altitude and Azimuth of the sun for the same time and space, but different equator and equinox.

Calculations have been made for the sun for each day of November 2020. Full calculation criteria can be fine in each file.

[alt_az_mean_j2000.txt](https://github.com/skyfielders/python-skyfield/files/5575489/alt_az_mean_j2000.txt)

[alt_az_CIRS.txt](https://github.com/skyfielders/python-skyfield/files/5575491/alt_az_CIRS.txt)

[alt_az_true_of_the_date.txt](https://github.com/skyfielders/python-skyfield/files/5575492/alt_az_true_of_the_date.txt)

[alt_az_mean_of_the_date.txt](https://github.com/skyfielders/python-skyfield/files/5575493/alt_az_mean_of_the_date.txt)

Best,

**Comment by brandon-rhodes** [comment]
> … we are computing horizontal coordinates from the apparent coordinates, which they affect by epoch.

I cannot comment in detail without seeing your code, but because epoch also affects the calculated position of the observatory on earth, it would cancel out when Skyfield computed the altitude and azimuth:

* The observatory is located at a given longitude and latitude ITRS.
* If you want to do J2000: then you would transform the ITRS coordinate into a J2000 coordinate with lat/lon → xyz → precession → nutation → frame_bias → J2000. Then you could compare that position with a Solar System position, like `.observe()` does, and then adjust with `.apparent()` for aberration. Then, because you need altitude and azimuth, you need to rotate all the way back into coordinates local to the observer: J2000 → frame_bias → nutation → precession → then a final rotation by the latitude and longitude and position of the Earth.
* Or you could do everything equinox of date: lat/lon → xyz; compare with a Solar System position in the equinox-of-date system; then rotate back → lat/lon/Earth position → to get an altitude and azimuth.

Either way the answer should be the same, so I am not exactly sure what your code is doing that is causing the transform to fail to apply in both directions. Could you be more specific about what your code is doing? Thanks!

**Comment by dataadvisor** [comment]
That's a nice point. I did all my calculations online in the following web interface, which could be very helpful.
You can check by yourself too. This web interface even better and somehow more up-to-date than the JPL horizons interface. Please go ahead and play around and check how you can get more ideas about some new features.

[The Institute of Applied Astronomy of the Russian Academy of Sciences](http://iaaras.ru/en/dept/ephemeris/online/)

Science does not only belong to Americans 😁

Best,

**Comment by brandon-rhodes** [comment]
In the early years of Skyfield, I would add a new method to the position objects every time someone asked about a new coordinate system — which would force yet another "xyz" method to be added for this issue, too. But, happily, when dealing with planetary reference frames I added a more general pair of methods `frame_xyz(frame)` and `frame_latlon(frame)`, so that a single pair of methods could support as many planetary reference frames in the future as folks want to define.

So I realized that all we needed here was a new frame! You can import and use it like this, given a position `p`:
```
from skyfield.framelib import mean_equator_and_equinox_of_date
x, y, z = from_spherical(distance1.au, lat.radians, lon.radians)
```
This feature will be available in the next version of Skyfield. In the meantime, if you want to try it out, you can:
```
pip install https://github.com/skyfielders/python-skyfield/archive/master.zip
```
I don’t, alas, at the moment have the resources to track down why that web site is giving you two different sets of alt-az coordinates for the same object. On previous occasions when I have tried to figure out how a web site was coming up with a particular set of numbers, I have often spent hours only to get no answer; unless I happen to make a lucky guess and get exactly the same set of numbers back, there's often no clear way to figure out where they are coming from. If you ever have time to do your own investigation, though, and figure out how they are producing conflicting altitudes and azimuths for the same object, I would be interested in hearing — it seems that only at most one of the two coordinates could be correct, since if you point your telescope at a given altitude and azimuth, the object is either at the center of the field of view or not?
