### ISSUE TITLE
Question about TEME_to_ITRF

### ISSUE THREAD

**Issue by gimzmoe** [skyfielders/python-skyfield#489]
I think I'm missing something in the TEME_to_ITRF function.

I'm trying to feed state vectors (position - km) & (velocity - km/s) 
Out of a hunch I tried modifying my TEME input velocity to km/day which was closer but still off.

I assumed this function was a trasnformation, so it shouldn't change what the vectors are measuring, but maybe it is?

I'm unfamiliar with xp and yp, is the 
my sanity check example:
```
dt = datetime.datetime.utcfromtimestamp(time.time())
rTEME = numpy.random.rand(3)
vTEME = numpy.random.rand(3)
rITRF, vITRF = TEME_to_ITRF(dt, rTEME, vTEME)
print( range: %s - %s' % (numpy.linalg.norm(rTEME), numpylinalg.norm(rITRF))
print( range: %s - %s' % (numpy.linalg.norm(vTEME), numpylinalg.norm(vITRF))
```

**Comment by brandon-rhodes** [comment]
What is `teme_2_itrf()`? Could you share its code?

**Comment by gimzmoe** [comment]
Oops, **TEME_to_ITRF** is in sgp4lib.py I had written another wrapper for testing.
here is something else that demonstrates the question.
```
import time
import datetime
import numpy as np
from skyfield.api import load
from skyfield.sgp4lib import TEME_to_ITRF
from skyfield.constants import AU_KM, DAY_S

st = time.time()
dt = datetime.datetime.utcfromtimestamp( st )
rT = np.random.rand(3)  # assuming km
vT = np.random.rand(3) # assuming km/s
vTx = vT * DAY_S  # converts km/s to km/day
ts = load.timescale()

jd_ut1 = ts.tt(
    dt.year,
    dt.month,
    dt.hour,
    dt.minute,
    dt.second + dt.microsecond * 10**-6)

rI, vI = TEME_to_ITRF(jd_ut1.J, rT, vT)
print( '\n-- Position input: km  -- ')
print( '%s -> %s' % (np.linalg.norm(rT), np.linalg.norm(rI) ))
print( '\n-- Velocity input: km/s -- ')
print( '%s -> %s' % (np.linalg.norm(vT), np.linalg.norm(vI)) )

_rI, vIx = TEME_to_ITRF(jd_ut1.J, rT, vTx)

print( '\n-- Velocity input: km/day  -- ')
magnitude_vTx = np.linalg.norm(vTx)
magnitude_vIx = np.linalg.norm(vIx)
error = abs(magnitude_vTx - magnitude_vIx)
print( '%s - %s | error: %s km/day' % (magnitude_vTx,magnitude_vIx,error ))
```

**Comment by brandon-rhodes** [comment]
@gimzmoe — Thanks for the working example! I now understand your question. The answer is: that the ITRF frame is rotating. It's not simply another static frame at a different constant angle from TEME, but TEME is fixed in space, whereas ITRF is rotating once per day with the Earth. So:

* A constant vector in TEME, pointing at some fixed star, will have a big velocity in ITRF as the Earth swings beneath it.
* A constant vector in ITRF, pointing at, say, Boston, will have a big enough velocity in TEME to show Boston as entirely circling the Earth in a single day — hundreds of miles per hour, I think.
* In any in between cases, a big change will still happen, somewhere in between those two limiting cases.

So you should expect velocity to change hugely to reflect the Earth’s rotation; a star will appear to go many times the speed of light in the ITRF frame, as it orbits the Earth once per day. Does that explain the numbers you're seeing?

**Comment by gimzmoe** [comment]
*facepalm* I wasn't aware of all the new international frames, and the language I found about them seemed to me to have lots of implicit assumptions, somehow I drew the conclusion that ITRF was inertial... 

So for my problem, if I keep my stuff in TEME and only convert to ITRF when I need a terrestrial reference I should be okay.
I'll keep looking for myself, but can you recommend a function to shift between Earth and ICRS?

**Comment by brandon-rhodes** [comment]
I'm glad we've found the source of confusion!

It just so happens that I'm working this week on making the undocumented internal routines for conversion to and from ITRF easier for folks to get to. If you’ll follow along at #476, you should within the next few days see a reply from me outlining how the new feature will work. I’ll close this so we can continue any discussion over there.
