### ISSUE TITLE
'str' object has no attribute 'MT'

### ISSUE THREAD

**Issue by dataadvisor** [skyfielders/python-skyfield#504]
Hello Brandon,

I have run the following codes and I got the error that I mentioned below:
```python
t = ts.now()
e = ephemeris[399]
v = ephemeris[299]
ra, dec, _ = e.at(t).observe(v).apparent().radec(epoch='date') 
position = position_of_radec(ra.hours, dec.degrees, epoch='date')
const_counter = frequency_of_elements_of_a_list(constellation_at(position))
```

But If I am using ```epoch=t``` instead of ```epoch='date'``` everything goes well.

Error:

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-1bc796aa18af> in <module>
      3 v = ephemeris[299]
      4 ra, dec, _ = e.at(t).observe(v).apparent().radec(epoch='date') # epoch='date'
----> 5 position = position_of_radec(ra.hours, dec.degrees, epoch='date') # epoch='date'
      6 const_counter = frequency_of_elements_of_a_list(constellation_at(position))

D:\anaconda3\lib\site-packages\skyfield\positionlib.py in position_of_radec(ra_hours, dec_degrees, distance_au, epoch, t, center, target)
     51     position_au = from_spherical(distance_au, theta, phi)
     52     if epoch is not None:
---> 53         position_au = mxv(epoch.MT, position_au)
     54     return build_position(position_au, None, t, center, target)
     55 

AttributeError: 'str' object has no attribute 'MT'
```

**Comment by brandon-rhodes** [comment]
The `position_of_radec()` call does not support the special string value `'date'` because it has no way of knowing the date on which the RA and declination were measured in the sky. It has to be provided as an actual date.

I am unsure what adjustment you are trying to make by moving to RA, dec and back again. You can pass an apparent position directly to the routine (though note that the results will be invalid, I suspect; only astrometric positions should be supplied?):

```
p = e.at(t).observe(v).apparent()
print(constellation_at(p))
```

**Comment by brandon-rhodes** [comment]
As it’s now been a couple of months since my initial reply, I'm going to optimistically close this issue in the hopes that my suggested code was helpful. Feel free to comment here further, though, if something is still not working.
