### ISSUE TITLE
Thinking about the examples, a suggestion.

### ISSUE THREAD

**Issue by ajpmaclean** [skyfielders/python-skyfield#505]
In looking at comet_neowise_chart.py I wonder whether you could quickly knock up a new example for the conjunction of Jupiter/Saturn 12 Dec 2020 for a  topocentric position. The plot could show for a range of dates the positions of the two planets tracking across the starfield. It would be a nice example combining quite a few features of Skyfield. Just a suggestion if you have time!

**Comment by brandon-rhodes** [comment]
That's an interesting idea! I probably won’t have time to do it myself, alas; I did the comet chart because I genuinely needed the chart to find the comet at first, but I have been finding Saturn and Jupiter so easily on clear evenings that a chart has not been necessary.

But there are lots of diagrams in astronomy publications that do present topocentric compared-to-the-horizon charts, for examples for the apparitions of Venus and Mercury, and as yet no examples of how to do that in Skyfield. So let’s keep this issue open until we have something like that illustrated for Skyfield, whether that happens this year for next, and whether someone does it in time for the conjunction or not!

Thanks for the idea.

**Comment by brandon-rhodes** [comment]
A horizon-targeted plot is now part of the official documentation:

https://rhodesmill.org/skyfield/example-plots.html#charting-an-apparition-of-venus
