### ISSUE TITLE
almanac.seasons, Vernal Equinox, the Sun's declination is nonzero

### ISSUE THREAD

**Issue by andrey-nakin** [skyfielders/python-skyfield#537]
Hello Brandon

I'm getting a time of the vernal equinox and the corresponding Sun's equatorial coordinates as follows:

```python
#!/usr/bin/env python3
from skyfield import api, almanac
from skyfield.searchlib import find_discrete

ts = api.load.timescale()
eph = api.load('de421.bsp')
t1 = ts.utc(2021, 1, 1)
t2 = ts.utc(2021, 12, 31)
timings, seasons = find_discrete(t1, t2, almanac.seasons(eph))
for ti, si in zip(timings, seasons):
    if si == 0:  # Vernal Equinox
        e = eph['Earth'].at(ti)
        ra, dec, _ = e.observe(eph['Sun']).apparent().radec(ts.J2000)
        print(ti.utc_iso(), ra, dec)
        break
```

Output:

```
2021-03-20T09:37:29Z 23h 58m 54.91s -00deg 07' 03.8"
```

Shouldn't the declination be zero?

I'd like to spare your time, just let me know if this is an expected result?

**Comment by JoshPaterson** [comment]
`almanac.seasons` finds when the ecliptic longitude of date is 0, however line 13 prints the declination with the J2000.0 epoch. When I change line 13 to `ra, dec, _ = e.observe(eph['Sun']).apparent().radec('date')` I get this:
```
2021-03-20T09:37:29Z 23h 59m 59.99s +00deg 00' 00.3"
```
Which is much closer to 0, but I'm not sure why it isn't exactly 0.

**Comment by andrey-nakin** [comment]
Thank you, Josh, I realized my mistake.

> I'm not sure why it isn't exactly 0.

Yes, it's interesting.

**Comment by brandon-rhodes** [comment]
Thanks for jumping in with advice, @JoshPaterson!

> I'm not sure why it isn't exactly 0.

It’s because the ecliptic is merely the average plane of the Earth’s orbit, not the plane of its orbit in any given year. When Jupiter and Saturn are below the ecliptic plane, as they are this year, the Sun must balance them by riding above the plane. The Earth, having very small mass compared to the giants, rides along with the sun into positive z-axis territory above the ecliptic plane.

As it happens, the Earth is currently not quite as far above the ecliptic plane as the Sun is. Try this at the bottom of your script:
```
for planet in 'Sun', 'Earth', 'Jupiter barycenter', 'Saturn barycenter':
    a = eph[planet].at(ti)
    x, y, z = a.frame_xyz(framelib.ecliptic_frame).km.astype(int)
    print(planet, 'ecliptic Z coordinate:', z, 'km')
```
It prints:
```
Sun ecliptic Z coordinate: 18310 km
Earth ecliptic Z coordinate: 18090 km
Jupiter barycenter ecliptic Z coordinate: -9392393 km
Saturn barycenter ecliptic Z coordinate: -13674124 km
```
So the Sun is 18310 - 18090 = 220 km above us at the moment relative to the plane of the ecliptic. How big an angle does that subtend when viewed from Earth? Let’s print the Earth-Sun distance:
```
print(int(e.observe(eph['Sun']).apparent().distance().km))
```
Which is:
```
148985261
```
Dividing the Sun’s distance above us (relative to the ecliptic) by the distance between us, we should expect the Sun to have a positive ecliptic longitude of atan(220 / 148985261) / tau * 360 * 3600 = 0.30458219 arcseconds, which is the same value your program now prints.

I'll go ahead and close this issue, as I think all your questions are now resolved, but please comment with any further responses or questions!

**Comment by andrey-nakin** [comment]
Brandon,

one more relating question. What is the most correct way to determine the time when astronomical twilight becomes permanent, i.e. when The Sun no longer descents below -18 degrees?

How correct is the code below (`my_latitude` is my location's latitude):

```python
ts = api.load.timescale()
eph = api.load('de421.bsp')

def twilight_at(time):
    here = eph['earth'].at(time)
    _, dec, _ = here.observe(eph['sun']).apparent().radec('date')
    return my_latitude + dec.degrees - 90.0 > -18

twilight_at.rough_period = 180

t1 = ts.utc(2021, 1, 1)
t2 = ts.utc(2021, 12, 31)
timings, ss = searchlib.find_discrete(t1, t2, twilight_at)
```

**Comment by brandon-rhodes** [comment]
Your `rough_period` might be a bit too aggressive, as 180 only works for places for things like "is the Sun north of the equator" that flip from "yes" to "no" every half-year. For locations that might only spend a couple of weeks without twilight by your formula, a rough period of 180 could miss them; to catch periods of only, say, 2 weeks, try a very short `rough_period` like 7 days.

But: yes, your formula is the one I would have written too. I just drew a diagram, and got:

sun declination > 90° – my latitude – 18°

Which, rearranged, I think comes out the same as what you wrote down, so I suspect your routine will work.

**Comment by andrey-nakin** [comment]
> Your rough_period might be a bit too aggressive

Fixed. Thank you, Brandon!
