### ISSUE TITLE
HADec documentation.

### ISSUE THREAD

**Issue by mkbrewer** [skyfielders/python-skyfield#540]
While the new `apparent.hadec()` method is working well, in my opinion it is rather poorly documented. It only appears under `API Reference->Position methods and attributes`  as `ICRF.hadec()`. In fact, it should be documented just the same as `altaz()` with an entry under `Positions and Coordinates` including in the graph under `Apparent position only`, an entry under `API Reference->Position methods specific to one class`, and an entry under `API Reference->Apparent position relative to an observer`.

**Comment by brandon-rhodes** [comment]
When I rewrite some of the `Positions and Coordinates` page for #529 within the next couple of weeks, that whole graph might disappear — it was useful very early in the project's history, but I think I might prefer folks to use the main API docs page instead, and if the main API docs aren’t as good and can't yet serve as a replacement, then I think that means I need to improve them. Here are the sections that would serve the same purpose as the static graph:

* https://rhodesmill.org/skyfield/api.html#position-methods-and-attributes
* https://rhodesmill.org/skyfield/api.html#units

Let’s keep this issue open until either I have removed the big table from the main Positions documentation page, or have decided to keep it and have hand-added the `hadec()` method (and whichever other methods we find it’s missing because it doesn’t auto-update).

**Comment by mkbrewer** [comment]
The disappearance of the graph doesn't moot this issue. The new `apparent.hadec()` method should be documented just as `apparent.altaz()` is currently for those using equatorial mounts rather than horizontal mounts that may want to use this method.

**Comment by brandon-rhodes** [comment]
> The new apparent.hadec() method should be documented just as apparent.altaz()…

Ah, so you were not only concerned with its absence from the graph, but also with an asymmetry: that `altaz()` appears down in a subclass, while `hadec()` is up on the main class and thus in a separate section of the API docs. So they never appear alongside each other in auto-generated documentation, because different architecture decisions were made in their placement.

Back when I wrote `altaz()`, I thought that maybe I could lock things down so that `altaz()` would only ever be valid on one subclass and could live there. And that effort failed, and it now appears on two subclasses, both `Apparent` and `Geometric` (a duplication which has created a problem already: I forgot to add `Geometric.altaz()` to the “Position methods specific to one class” section of the main API doc).

When `hadec()` was requested, I had to study and reconsider the main position class and its subclasses, a question I mulled for a couple of weeks. Clearly subclasses were now trying to model two different design axes at once: the question “what kind of position is this, astrometric or apparent?”, and also the question “is this position centered on the Earth or a topocentric position with a local horizon and zenith attached?” Trying to model *n* states times *m* states with subclasses is a classic mistake, that I discuss on my Python Patterns web site:

https://python-patterns.guide/gang-of-four/composition-over-inheritance/

So I put `hadec()` on the main position class, and it will work or not depending on whether the position’s center has a longitude and latitude or not. (I should really arrange for a prettier exception explaining the situation if the position wasn't topocentric.)

And I think that `altaz()` belongs there as well. Instead of trying to control every possible code path that could produce a position with a latitude/longitude location as its center, and shunt those positions over to being subclasses of a specific class, I think that like `hadec()`, the `altaz()` method should move up on to the main position class. That will make it less fragile: it will automatically be available everywhere it can possibly be validly used. And it will eliminate what currently is the duplication of the exact same method living on two different classes.

So let's add that simplification as a goal of this issue as well. That will pop `altaz()` up out of the “Position methods specific to one class” section and put it proudly next to `hadec()` as its peer.

**Comment by brandon-rhodes** [comment]
I now remember the ideal that inspired the original placement of `altaz()` on `Apparent`: I didn’t want to support expressions like `(earth + town).at(t).observe(mars).altaz()` that would have folks producing altitudes and azimuths at which objects cannot in fact be observed because aberration and deflection have not been applied.

I have never yet (that I recall) received a complaint about its absence on the `Astrometric` class, so the maneuver seems to have worked fine.

So maybe the solution is to move `hadec()` on to `Apparent` and `Geocentric` classes. (The latter class behaves like a “treat this as apparent in-fact” position, since often it’s a satellite position that’s not precise enough to care about even light travel time, but that’s a bit imprecise on Skyfield’s part.)

**Comment by brandon-rhodes** [comment]
I've finally had time to sit down and write a Coordinates chapter, that shows how to use the `hadec()` method. It was committed here:

2b3e23d065b1610c5eceb5110c2c272255990913

and should also now be on the website.

Several other parts of this issue's discussion were useful and might lead to further future improvements, but since the original issue was about the lack of documentation, I'm going to close the issue in celebration.

**Comment by mkbrewer** [comment]
Now if I could only convince you to move `hadec()` from `ICRF.hadec()` down to `Apparent.hadec()` under `Astronomical Positions` and from under `Generic ICRF position` to `Apparent position relative to an observer` under `API Reference — Astronomical Positions`. Having it under `ICRF` makes no sense to me as it is aligned with the `ITRS` as is `altaz()`. It is, after all, just a rotation of `altaz()` by `90 - observer latitude`.
