### ISSUE TITLE
need a way to pass gravity model to TLE loader

### ISSUE THREAD

**Issue by marioTjTespinosa** [skyfielders/python-skyfield#544]
I am loading a large TLE file using:  satellites = load.tle_file(args.tle_catalog)
But I want those satellites to use WGS84 gravity model for propagation, and it does not seem the be a way to pass this to the loader.

**Comment by brandon-rhodes** [comment]
In that case we will indeed need to look for an alternative way to specify the WGS84 model. To make sure I am clear about the problem: the TLE lines themselves offer no information about the model to use? The fact that they need a different model than usual is, so to speak, delivered "out of band" from the data in the TLE lines themselves?

**Comment by marioTjTespinosa** [comment]
Correct, the TLE does not specify what gravity model to use. As far as I understand, the SGP4 algorithm defaults to WGS72, but you normally can specify which gravity model to use. I do not remember if SkyField uses this (https://pypi.org/project/sgp4/) implementation of sgp4 underneath, but you can see on that page you can call: 
>>> from sgp4.api import WGS72OLD, WGS72, WGS84
>>> satellite3 = Satrec.twoline2rv(s, t, WGS84)
and specify you want to use WGS84 as the gravity model.
It would be nice to do have the option on the TLE loader so all the EarthSatellite instances are configured with that gravity model.

**Comment by brandon-rhodes** [comment]
For situations where satellite creation needs to be tweaked beyond the defaults, it may be better to teach programmers how to use the underlying `sgp4` library, than it would be to add to Skyfield every combination of options that the underlying library offers or might additionally offer in the future. Try this code, which uses a constructor that lets Skyfield accept an already-built satellite object instead of creating one itself:

```
from sgp4.api import Satrec, WGS84
from skyfield.api import load
from skyfield.sgp4lib import EarthSatellite

line1 = "1 37820U 11053A   14314.79851609  .00064249  00000-0  44961-3 0  5637"
line2 = "2 37820  42.7687 147.7173 0010686 283.6368 148.1694 15.73279710179072"

ts = load.timescale()
satrec = Satrec.twoline2rv(line1, line2, WGS84)
sat = EarthSatellite.from_satrec(satrec, ts)

print(sat)
print(sat.epoch.utc_strftime())
```

Does it create a satellite that shows the behavior you need? If so, then I would like to add this to the Skyfield documentation — I think that, in any situations beyond the default, programmers will have more power and control if they use the underlying library directly.

If looping across a file and grabbing the lines that start with "1" or "2" is tedious (and if programmers can't easily find and use the loop that Skyfield uses for it), then we could additionally break out that logic as a separate Skyfield routine. Currently the how-to-find-the-TLE-lines logic is trapped in `parse_tle_file()` with the call to the constructor.

**Comment by brandon-rhodes** [comment]
@marioTjTespinosa — As I never heard back from you, I'm hoping that the code I wrote for you wound up working in your project and letting you move forward again. I've added the sample code to the main documentation so that other developers can now do the same thing!
