### ISSUE TITLE
EarthSatellite and from_satrec generate different results

### ISSUE THREAD

**Issue by dcajacob** [skyfielders/python-skyfield#554]
I'm not sure how to classify this. You can generate a satellite with the EarthSatellite TLE constructor and you can use the model variables from that satellite to create an ideally identical satellite using the from_satrec constructor from SGP4. If you do things carefully, the resulting epochs are the same, but propagated results at simultaneous epochs are slightly off. This seems to be because the jdsatepochF is not rounded in the "from_satrec" object, but it is in the original TLE-based object. I suspect that is where the difference comes from. Incidentally, in the code below, if I don't apply the rounding to the epoch in the sgp4init call, the position difference is much worse, but still sub-meter. It seems like there ought to be some way to create a satellite object that would be identical to what a TLE would generate. The only difference seems to be in the jfsatepochF.

```
import numpy as np

from skyfield.api import EarthSatellite, load
from sgp4.api import Satrec, WGS72

ts = load.timescale()

line1 = '1 25544U 98067A   14020.93268519  .00009878  00000-0  18200-3 0  5082'
line2 = '2 25544  51.6498 109.4756 0003572  55.9686 274.8005 15.49815350868473'
satellite = EarthSatellite(line1, line2, 'ISS (ZARYA)', ts)

satrec = Satrec()
satrec.sgp4init(
    WGS72,           # gravity model
    'i',             # 'a' = old AFSPC mode, 'i' = improved mode
    satellite.model.satnum,               # satnum: Satellite number
    round(satellite.model.jdsatepoch + satellite.model.jdsatepochF - 2433281.5,8),       # epoch: days since 1949 December 31 00:00 UT
    satellite.model.bstar,      # bstar: drag coefficient (/earth radii)
    satellite.model.ndot, # ndot: ballistic coefficient (revs/day)
    satellite.model.nddot,             # nddot: second derivative of mean motion (revs/day^3)
    satellite.model.ecco,       # ecco: eccentricity
    satellite.model.argpo, # argpo: argument of perigee (radians)
    satellite.model.inclo, # inclo: inclination (radians)
    satellite.model.mo, # mo: mean anomaly (radians)
    satellite.model.no_kozai, # no_kozai: mean motion (radians/minute)
    satellite.model.nodeo, # nodeo: right ascension of ascending node (radians)
)

alt_sat = EarthSatellite.from_satrec(satrec, ts)

print("Epoch diff: ", np.abs(alt_sat.epoch - satellite.epoch) * 86400)
print("Pos diff (m): ", (satellite.at(satellite.epoch).position.km - alt_sat.at(alt_sat.epoch).position.km) * 1000)
print("Rounded epoch fraction: ", satellite.model.jdsatepochF)
print("Not rounded epoch fraction: ", alt_sat.model.jdsatepochF)
```

**Comment by brandon-rhodes** [comment]
> It seems like there ought to be some way to create a satellite object that would be identical to what a TLE would generate.

That would be nice! Let’s make it happen. It’s currently impossible because all that `sgp4init()` receives is `epoch` some of whose bits have to be busy giving the date and so only the remainder can specify the fraction within the date. This means that the epoch time from `sgp4init()` is truncated early, no matter how carefully you craft the float, whereas the epoch date pulled directly from the TLE can have as many bits as it wants:

```
import struct
def bits(num):
    bytes = struct.pack('!d', num)
    return ''.join(bin(c).replace('0b', '').rjust(8, '0') for c in bytes)

sat1 = satellite.model
sat2 = alt_sat.model

print(bits(sat1.jdsatepochF))
print(bits(sat2.jdsatepochF))
```

If the above code is added to the bottom of your script (and, THANK YOU for putting together a working script I could run, it made it easy to tackle your question), then we get out:

```
0011111111101101110110001000111010011100100100000110111011111001
0011111111101101110110001000111010011100100100001000000000000000
```

As you can see, the original satellite’s time-of-day fraction has bits all the way to the bottom to draw it as close as possible to the decimal number `0.93268519`. But the `sgp4init()` satellite could do no better than to copy bits from `epoch` until they ran out, leaving all zeros down at the bottom. And while that's a very exact floating point number, it's not particularly close to the decimal fraction you want.

Possibilities:

1. The extra code I added to `sgp4init()` to set `jdsatepoch` and `jdsatepochF` could start internally rounding — it could say “oh, come on, the person probably wanted this to fall on an exact hundred-millionth of a day!” and round the second bit pattern shown above so that it becomes the first one. While that would break the library’s behavior for anyone who really did want to provide an epoch and get back the exact binary fraction — there might not be anyone who needs that?
2. I could add an extra optional argument to `sgp4init()` that provides more precision for the day fraction. Let’s not do that. Interfering with the argument lists of industry-standard routines is not a direction I want to move!
3. I could mark `jdsatepoch` and `jdsatepochF` as read-write rather than read-only, so you could go set them to whatever you want once `sgp4init()` is done. I had worried about people building invalid satellites when I first set them read-only, but it’s really against the spirit of Python to be locking things down (it’s more like a private method in one of those other languages, something I'm officially *supposed* to be against), so it would be consistent with my public talks for me to make all those attributes writeable.
4. Better yet, I could do both 1 and 3, so that it Just Works™ for most people, and so that other folks who don’t want the rounding can undo it afterward by assigning a different float to `jdsatepochF`.

And yet.

Numbers 1 and 4 would change existing behavior, and throw around bits where the caller did not themselves place bits. At this point, `sgp4` is probably used in enough projects that it shouldn't go changing the satellites it returns. So, I think number 3 is the winner here.

Do you agree that a writable `jdsatepochF` would solve your problem, and is probably the most direct means to do so?

**Comment by dcajacob** [comment]
I think making the jdsatepochF parameter writable would indeed solve my problem. Thanks! In fact, I naively tried writing to the orbital parameters first (even knowing about the from_satrec constructor). I appreciate your thoughtful analysis and the great library!

**Comment by dcajacob** [comment]
I was able to test the commit and it works great!

**Comment by brandon-rhodes** [comment]
Great! I'll see about doing a release today.

**Comment by karatemir** [comment]
I tried @dcajacob's snippet and two satellite's don't match unless `round(,8)` is used. What is the principled way to create an exact replica of a satellite that was created by a TLE? I understand that `jdsatepochF` can be overwritten now but how does that help?

**Comment by brandon-rhodes** [comment]
@karatemir — Which version of Skyfield and sgp4 are you using? Here's what I get when I run his script:

```
Epoch diff:  0.0
Pos diff (m):  [0. 0. 0.]
Rounded epoch fraction:  0.93268519
Not rounded epoch fraction:  0.93268519
```
