### ISSUE TITLE
Alternate EOPs

### ISSUE THREAD

**Issue by mkbrewer** [skyfielders/python-skyfield#555]
I just learned that you don't like private methods, so how about removing the underscore from _build_timescale_arrays(), so that I don't need to feel guilty about loading the IERS EOP 14 C04 DUT1s to do direct comparisons with Astropy which uses these rather than finals2000A.all? Another thing that you might consider here is to raise an error if  _build_timescale_arrays() is called with dates beginning prior to January 1, 1973 rather than just returning garbage due to the 12 leap seconds that are built-in.

**Comment by brandon-rhodes** [comment]
Good question: the name is private because its API is expected to change soon. The arrays it returns have an idiosyncratic format that I don’t think makes sense for a public API, and that I am planning on changing. Thus a comment from the current Timescale constructor:
```
        # Work-in-progress: make a less crazy leap-second table, that
        # does not need the -inf and +inf at the ends.
```
I have already improved some parts of the Time and Timescale to use a simpler array, and once I've pushed those changes through to the rest of their code, the old format will disappear, and I'll pivot `_build_timescale_arrays()` to the new permanent format, and at that point will remove the leading underscore.

(If you'd like, I can keep the old `_build_timescale_arrays()` around for a few years and have the new different `build_timescale_arrays()` alongside it, so your old code keeps working, to give you time to migrate.)

Let’s keep this issue open to track my progress. At the moment I have several other balls in the air (I’m in the middle of rewriting the JPL ephemeris documentation after some user comments revealed that folks didn’t understand it; in a much smaller matter, speaking of underscores, I'm going to come up with a public name for the no-sanity-check `._degrees` and `._hours` attributes of angles since the underscore discourages their use; I'm still in the process of designing how multiple observers and multiple targets can work at the same time so Josh’s pull requests can make progress; etc), but I'll see if I can squeeze in some finishing-up work on the Timescale within the next few weeks.

**Comment by mkbrewer** [comment]
No need to keep the old function around just for me. I can keep up with the way things evolve so long as there is still a way for me to use alternate EOPs.

**Comment by brandon-rhodes** [comment]
In the above commit, I've made the function public! Also, the crazy old leap second table is gone, so you might find an improvement (or at least a change?) in the data returned in the pre-1973 case you mentioned, but I haven't had time to test that myself.

**Comment by mkbrewer** [comment]
As currently written, there will be no change. The problem arises from the fact that you choose to use the Bulletin A/B daily estimates rather than the more accurate retroactive C04 solution from the IERS as described here:[ ftp://hpiers.obspm.fr/iers/eop/eopc04/C04.guide.pdf](url). Since this is what Astropy uses, I need to substitute these values in order to do a direct comparison between Skyfield and Astropy. The data file that they use: https://datacenter.iers.org/versionMetadata.php?filename=latestVersionMeta/224_EOP_C04_14.62-NOW.IAU2000A224.txt goes back to January 1st, 1962.  Now, I know that you have no way to deal with the small increments introduced before 1972, so data before then is garbage to Skyfield, but data from January 1st, 1972 onward would be usable if not for the fact that your big jump calculator detects the two leap seconds introduced in 1972. Since you add 12 leap seconds starting January 1st, 1973, all data from 1972 onward is off by 2 seconds. I am aware of this problem, so it's not an issue for me. I just mask off all data before January 1st, 1973. But it is a bit of a gotcha as I needed to carefully study your code to see where that 2 second error was coming from. I'd suggest adding a comment line that explicitly states that you are adding 12 leap seconds so any alternate data must begin between January 1st and December 31st, 1973. In fact, it would be relatively easy to detect if this is not the case and throw an exception also.

**Comment by brandon-rhodes** [comment]
I've added code to at least protect for the moment against duplicating those two leap seconds if they're instead detected from the data.

Handling the smaller jumps pre-1972 would indeed involve some revision of the assumption built into the UTC←→TAI code that offsets are always a multiple of 1.0. Maybe I should tackle that someday, since there's a request on the table for a HORIZONS-style “UT” timescale that combines ancient UT1 with recent UTC, and in between would probably best follow the old stepped standard time that preceded UTC.

**Comment by mkbrewer** [comment]
Unfortunately, the change you made won't help resolve the problem as it lies here:
```
    tt_minus_utc = np.cumsum(leap_second_mask) + 32.184 + 12.0
```
This causes `dut1` to be off by 2 seconds if data from January 1st, 1972 is loaded.

Regarding pre-1972 dates, should you wish to implement these, this file from SOFA may be helpful: [dat.c.txt](https://github.com/skyfielders/python-skyfield/files/6272830/dat.c.txt)
