### ISSUE TITLE
Support for adding and subtracting deltas to Time objects?

### ISSUE THREAD

**Issue by joncox123** [skyfielders/python-skyfield#568]
It seems that Skyfield does not support adding or subtracting increments of time (e.g. timedelta) to a Time object. For example, say you have a Time object and you want to increment it exactly 0.0000038001 seconds, you would like to do:

ts.now() + timedelta(seconds=0.0000038001) # or something similar

This would give you the time by a precise amount in the future or past, at the reference frame of the Time object. Is this functionality already available? If not, it would be appreciated. Right now, I am rolling my own implementation.

P.S. converting back and forth between datetime objects and Time objects can get you this functionality, but the loss of precision is unacceptable because the resolution defaults to microseconds. I need double precision second resolution.

**Comment by brandon-rhodes** [comment]
Thanks for the suggestion! There are a few different ways, even with the current code, to do increment and decrement of a time. Could you outline the situation you're in that requires you to adjust times, since that might affect what the best solution for your case looks like?

A problem with the expression you suggest is that:

* It's ambiguous with which timescale to do the arithmetic with. Skyfield couldn't tell whether those are TT seconds or TDB seconds or UT1 seconds.
* But maybe we could choose the reasonable default of TT seconds. There's then the problem of what if the timedelta also has a nonzero number of days. Are those TT/TAI days, or UTC days with their leap second included?

Wanting to avoid those ambiguities, Skyfield users have typically pulled out the timescale they want to increment (like TT, or TAI, or UTC), added their value to it, then built a new Time object. Let's see if your situation suggests a solution that will make sense!

**Comment by cruisen** [comment]
For a `timedelta(seconds=0.0000038001)` see comments above.

However for something like`timedelta(days=5)`  using `ts.from_datetime(datetime.timedelta(days=5))` appears sufficient. Or am I missing something?

**Comment by brandon-rhodes** [comment]
As you'll see in the above commit, I've added this feature to Skyfield and it should appear in the next release. Thanks for suggesting it!
