### ISSUE TITLE
Wrong twilight calculations?

### ISSUE THREAD

**Issue by eddienko** [skyfielders/python-skyfield#569]
I am trying to use this package to calculate twilight times and I seem to have incorrect values. Example below:

```
import datetime as dt
from pytz import timezone
from skyfield import almanac
from skyfield.api import N, W, wgs84, load

zone = timezone('UTC')
now = zone.localize(dt.datetime.now())
midnight = now.replace(hour=0, minute=0, second=0, microsecond=0)
next_midnight = midnight + dt.timedelta(days=1)

ts = load.timescale()
t0 = ts.from_datetime(midnight)
t1 = ts.from_datetime(next_midnight)
eph = load('de421.bsp')
bluffton = wgs84.latlon(51.509865 * N, 0.118092 * W)  # London
f = almanac.dark_twilight_day(eph, bluffton)
times, events = almanac.find_discrete(t0, t1, f)
for t, e in zip(times, events):
    tstr = str(t.astimezone(zone))[:16]
    print(tstr, ' ', almanac.TWILIGHTS[e], 'starts')
```

The output is

```
2021-03-19 04:12   Astronomical twilight starts
2021-03-19 04:52   Nautical twilight starts
2021-03-19 05:31   Civil twilight starts
2021-03-19 06:05   Day starts
2021-03-19 18:12   Civil twilight starts
2021-03-19 18:45   Nautical twilight starts
2021-03-19 19:24   Astronomical twilight starts
2021-03-19 20:05   Night starts
```

Comparing with http://astro.ukho.gov.uk/nao/miscellanea/birs2.html this seems to be wrong (the morning ones are correct, the evening ones have right times wrong labels, "Night starts" should be "Astronomical twilight"

**Comment by brandon-rhodes** [comment]
> the evening ones have right times wrong labels, "Night starts" should be "Astronomical twilight"

Astronomical twilight starts as nautical twilight ends. The order is:

Day – Civil – Nautical – Astronomical – Dark

The table you shared has, for London, astronomical twilight last from 19:25 (when nautical ends) til 20:06.

Skyfield has 19:24 through 20:05, only a slight difference.

You might have been confused by the UK table's layout, and the fact that it doesn't make clear the series of events in the evening as the three twilights give way to each other?

I wonder if I should change those labels in the example code, so that `Astronomical twilight starts` could be `Nautical twilight ends`? Would that have helped clear up your confusion about how the UK table related to the Skyfield output?

**Comment by brandon-rhodes** [comment]
Another point in favor of "end of nautical" rather than "start of astronomical" is that, in one sense, it's nautical twilight all day long, if one considers nautical twilight to mean simply "above -12° altitude" (and not "between -12° and -6°"). So if "nautical twilight" means at least a certain amount of light, it lasts all day.

I'll see if I can update the code example in the docs to reflect that.

**Comment by brandon-rhodes** [comment]
There, I've updated the docs so that at the next release, the example code will use the more conventional starts/ends terminology. It makes the code example a bit more complex but I think people will appreciate it; thanks for pointing out the awkwardness of the previous example code!
