### ISSUE TITLE
doppler shift with skyfield

### ISSUE THREAD

**Issue by ricky-bos** [skyfielders/python-skyfield#590]
Hello, 

i want to calculate the doppler shift of a satellite signal using skyfield.

I came across this entry at stackoverflow [1](https://stackoverflow.com/questions/55232097/how-to-find-satellite-relative-velocity-in-skyfield) and are calculating the relative velocity as explained.

Here is my output for the OSCAR A7
<img width="232" alt="Bildschirmfoto 2021-05-07 um 12 36 43" src="https://user-images.githubusercontent.com/61737504/117437935-2d1bff80-af31-11eb-9bcc-b6146ab5920d.png">

This shall be the relative velocity between ground station and satellite.  Doesn't the speed have to be positive as well as negative (since the satellite first moves towards the ground station and then moves away from it) ?

Plz help. I am missunderstanding something.

**Comment by Bernmeister** [comment]
I have no idea how to answer the question; to assist someone who might, would be great to include a self contained test script that they might run to investigate further.

**Comment by brandon-rhodes** [comment]
I suspect that you are confusing relative velocity with radial velocity. That Stack Overflow question is about relative velocity: how to create a vector showing where the satellite is moving relative to the observer. But like all velocities, its magnitude is positive, in the direction the satellite is moving. Is it likely that you instead want the radial velocity, which isn't a vector but a single scalar quantity indicating whether the satellite is approaching or receding?

**Comment by ricky-bos** [comment]
I've always read relative speed when it comes to calculating the Doppler shift. E.q. [Calculating Doppler Shift for satellites](https://ham.stackexchange.com/questions/1509/calculating-doppler-shift-for-satellites). 

When the satellite is approaching the Doppler shift decreases to zero and when it moves away the Doppler shift increases into the negative. Can the radial speed be determined with Skyfield ?

**Comment by brandon-rhodes** [comment]
What if you tried calling https://rhodesmill.org/skyfield/api-position.html#skyfield.positionlib.ICRF.frame_xyz_and_velocity passing your geographic location as the frame, which would give you two vectors in the alt-az system of coordinates? Then the velocity in the z direction might be radial velocity. (I've never tried myself, so check the other axes too in case I have x,y, and z mixed up in my head.)

**Comment by ricky-bos** [comment]
Thank you for the suggestion :)

I wrote the following function passing position objects of the satellite and ground station created with the at() method.

```
def get_radial_velocity(self, tx_pos, rx_pos):
        # direct line of sight
        slant_icrf  = tx_pos - rx_pos
        slant       = slant_icrf.position.km
        unit_slant  = slant / np.linalg.norm(slant)

        # satellite velocity
        vel0        = tx_pos.velocity.km_per_s
        v_rel0      = length_of(vel0)
        unit_vel0   = vel0 / np.linalg.norm(vel0)

        # ground station velocity
        vel1        = rx_pos.velocity.km_per_s
        v_rel1      = length_of(vel1)
        unit_vel1   = vel1 / np.linalg.norm(vel1)

        # angular deviation of the satellite from the direct line of sight
        theta0  = np.arccos(np.dot(unit_vel0, unit_slant))

        # angular deviation of the ground station from the direct line of sight
        theta1  = np.arccos(np.dot(unit_vel1, unit_slant))

        # radial velocity
        v_rad   = v_rel0 * np.cos(theta0) + v_rel1 * np.cos(theta1)

        return v_rad

```
The S curve can now also be clearly seen in the waterfall diagram. :)
<img width="912" alt="Bildschirmfoto 2021-05-10 um 09 03 17" src="https://user-images.githubusercontent.com/61737504/117618800-c421cb00-b16e-11eb-8c47-687046aa603c.png">

**Comment by brandon-rhodes** [comment]
I'm glad you were able to work out a realistic-looking result with unit vectors! I'll be interested to hear whether the unit-vector numbers you've produced match the z-axis of the `frame_xyz_and_velocity()` method, or whether my approach gives a different number.

**Comment by ricky-bos** [comment]
I'm still using the version 1.22 of skyfield. I need to update to verify your approach. I will give it a try next week.

**Comment by trc2203** [comment]
Hi Brandon,

I'm attempting a similar thing and (perhaps naively) thought that subtracting my ground station from my satellite at time t and then getting the velocity would give me my satellite's velocity relative to my ground station. This didn't give me the result I expected so I also tried the `frame_xyz_and_velocity()` method you suggested. This also didn't seem right, both of these options result in just one of the coordinates changing (x and z respectively) in a linear fashion - I expected the relative velocity to change less when the satellite was further away.

The method I came up with that gave me the result I wanted was to use the `distance()` method and then differentiate using numpy:

```python
dists = []
for i in range(10):
    for j in range(60):
        dt = ts.utc(2021, 5, 21, 18, 50 + i, j)
        comp = mysat.at(dt) - tx_loc.at(dt) # mysat is an EarthSatellite, tx_loc = wgs84.latlon(lat, lon)
        dists.append(comp.distance().km)
vels = np.gradient(dists)
plt.plot(vels)
plt.xlabel("Seconds")
plt.ylabel("Relative velocity (km/s)")
```
![Figure_1](https://user-images.githubusercontent.com/37266776/123317824-5c5cef00-d526-11eb-8d5e-47ce2a2c2916.png)

However this isn't ideal because I need to propagate with sufficiently small timesteps over the time period I'm interested in to get an accurate velocity result, so I'd like to know if there's a way to calculate this relative velocity at any given instant without having to do this. Perhaps I'm misunderstanding what I'm actually calculating by subtracting my objects and getting the velocity?

**Comment by brandon-rhodes** [comment]
> This didn't give me the result I expected so I also tried the frame_xyz_and_velocity() method you suggested.

Oh — that makes sense! My earlier answer was typed as I was imagining the satellite directly overhead, in which case the z-coordinate is indeed the range. But, with a little more thought, I now see that when the satellite is *not* aligned with the azimuth-nadir axis, none of the three east/north/up coordinates will necessary be the range. So ignore what I said earlier!

> differentiate using numpy to get the rate of change

Yes! That would work, but does have the problem (small step size) you mention.

> if there's a way to calculate this relative velocity

It feels like we want polar coordinates centered on the observer. What about calling the position's `frame_latlon_and_rates()` method with pretty much any coordinate system as the argument? The three resulting coordinates should be lat, lon (meaning whatever those mean in the coordinate system), and distance. So something like:

    _, _, sat_range = comp.frame_latlon_and_rates(some_frame)

— might give you the derivative you want? I can't try writing exact code without having a full script to work with, but see if you can get something like that working.

Oh, and, I also can't test this without a full script, but I think this might replace your loop:

    t = ts.utc(2021, 5, 21, 18, 50, np.arange(10 * 60))
    pos = (mysat - tx_loc).at(t)
    _, _, sat_range = pos.frame_latlon_and_rates(tx_loc)

**Comment by brandon-rhodes** [comment]
As you'll see in the commit message above, I decided this was a good enough question that it should be answered in the documentation, so:

bd535f9401ef16d5ae7285523a4fe6c246afd62a

Could someone try the sample code out and let me know if it looks like a real Doppler range rate, before I push this new version of the docs to the website? Thanks!

**Comment by trc2203** [comment]
Brandon, I massively appreciate you responding so quickly and helpfully! I tried the code you suggested and it worked perfectly. I could post the graph that I get with it but it would be pointless but it looks identical to the above. The actual numbers I get are all very close to my method but slightly different (no more than 1m/s out) which I assume is just because this method is slightly more accurate (as well as being simpler and more elegant). I also hadn't realised I could provide a list of times directly to the `at()` method, or that I could go beyond 60 in the seconds field, that's really convenient.

**Comment by brandon-rhodes** [comment]
I'm glad it worked! I've pushed the new version of the docs to the web site, so it should show up within a few minutes.
