### ISSUE TITLE
Tweak the "name" input in EarthSatellite init

### ISSUE THREAD

**Issue by bobbyfrasier** [skyfielders/python-skyfield#599]
In a 3-line TLE, the first line (usually called "line0") gives the name of the satellite.
In the current version of Skyfield, the name of the satellite has to be given directly to the `name` parameter.

The problem is that the line0 is written differently depending on the source of the TLE. For example, TLEs line0 coming from Celestrack seem to be written as a 24 char string with only the name of the satellite while TLEs line0 from SpaceTrack have a leading "0 " before the name of the satellite and no char limit.

Therfore it could be nice to have a parser on the parameter "name" (or "line0") like for example:

        if len(line0) == 24:  # Celestrak
            name = line0
        elif line0.startswith('0 '):  # Spacetrack 3-line format
            name = line0[2:]
        else:
            name = None

**Comment by brandon-rhodes** [comment]
Skyfield leaves its Earth satellite object as simple as possible — generally, class constructors in Python try to use the parameters they’re given without much interpretation, since if special source-specific logic lives in the constructor then it (in this example) becomes impossible to create a satellite object whose name does happen to start with `'0 '`.

Instead, Skyfield puts the I/O logic in its `parse_tle_file()` routine. Here’s the logic for removing the leading zero:

https://github.com/skyfielders/python-skyfield/blob/aa59e2d4711c3a95804170889f138402edbf4237/skyfield/iokit.py#L477-L483

Where in the documentation were you reading when you needed this feature? I'd like to add a mention of `parse_tle_file()` there so that other folks can find the input-parsing logic more easily. Thanks!

**Comment by brandon-rhodes** [comment]
As this issue has been idle for a few weeks, I'm going to close it — but feel free to continue commenting if at any point you come back, and have an answer to my last question. Thanks!
