### ISSUE TITLE
Event order bug in EarthSatellite.find_events()

### ISSUE THREAD

**Issue by shawnperdue** [skyfielders/python-skyfield#600]
Found a minor bug in the output order of events in EarthSatellite.find_events(): when the rise and summit times are the same, it lists the summit time before the rise time.

Recreate using this TLE:

1   900U 64063C   21147.18413222  .00000266  00000-0  27497-3 0  9992
2   900  90.1648  34.0968 0029447 100.6955  23.6656 13.73535518817635

Propagate across UTC 2 Sept 2021 10:00 to 2 Sept 2021 11:00, using a horizon of 30 deg.

**Comment by brandon-rhodes** [comment]
Thanks for the report! This looks similar enough to #561 that I suggest we move discussion over there, since in that case an example script was provided that folks can try out. One solution has been suggested, and a pull request offered. I'm not yet convinced that it's a complete enough fix, but you might take a look at it for ideas.
