### ISSUE TITLE
Feature Request: Add moon phase information

### ISSUE THREAD

**Issue by Bernmeister** [skyfielders/python-skyfield#61]
Hi Brandon,

I would like to be obtain moon phase information similar to what PyEphem provides:

ephem.next_full_moon
ephem.Moon().phase

and similar please.

Thanks,

Bernard.

**Comment by tritium21** [comment]
there has been a task in TODO to make an example ipython notebook for that for about a year.  It apparently can be done with a little help from scipy.  Because of the added dependency of scipy, I dont think it would be added to the core of skyfield, but someone could write a third party module to wire it all together, or this could be documented as a how-to.  I have not been able to find the time to learn enough math to read the scipy documentation, so I cannot actually offer this.

as an aside, can I say as a developer interested in astronomy, and not an astronomer who needs just happens to need software... ipython notebookes are almost useless to me.  So as a source of how-to documentation, it leaves a lot to be desired.

**Comment by brandon-rhodes** [comment]
What do you find to be the most annoying problem with sample code delivered as a notebook?

**Comment by tritium21** [comment]
Having to install ipython.

**Comment by brandon-rhodes** [comment]
And so it would be ideal for your use case if, however much a notebook might help illustrate the use of a feature and how it could be displayed, the actual logic were rolled into plain `.py` files shipped as part of Skyfield. I will keep that in mind when I tackle moon phases.

**Comment by tritium21** [comment]
That is ideal for me but I may be the only one; people seam to love ipython.

**Comment by brandon-rhodes** [comment]
I have just released Skyfield 1.8 with support for moon phases and percent illumination:

http://localhost:8002/_build/html/almanac.html
http://localhost:8002/_build/html/api-almanac.html

Enjoy!

**Comment by barrycarter** [comment]
Hate to re-open for such a minor thing, but I'm pretty sure you didn't mean to link to localhost port 8002?

**Comment by brandon-rhodes** [comment]
Fixed! :)

(And, note that commenting doesn't re-open the issue, so I don't need to re-close it or anything)
