### ISSUE TITLE
Question about the longitude calculation in toposlib.py

### ISSUE THREAD

**Issue by troyrock** [skyfielders/python-skyfield#632]
This is a question rather than an issue.  I'm looking at the longitude calculation done in toposlib.py.  The current code has:

`lon = (arctan2(y, x) - pi) % tau - pi`

I don't understand all of the extra "stuff."  Why not just:

`lon = arctan2(y, x) `

Thanks for your patience and help.

**Comment by brandon-rhodes** [comment]
It changes the range of the output to be -𝜋 → +𝜋 that’s 180° offset from the output of `arctan2()`. I recommend tossing several dozen possible angles at the formula to see how it works, and I recommend applying one operator at a time until you've rebuild the original expression, but: the first subtraction offsets the angle by 𝜋; then the modulo resets the value to 0→2𝜋; then the second subtraction offsets the angle again bringing in into the range -𝜋 → +𝜋.

Since twice 𝜋 is a circle, subtracting 𝜋 twice (hopefully!) makes no change to the angle itself, so the input and output angle will be the same angle.

**Comment by troyrock** [comment]
Thank you for your quick reply and also the great tool!
