### ISSUE TITLE
I know how to calculate the difference in angles between 2 planets. However, I want to get rahu and ketu positions as well which are not in the list

### ISSUE THREAD

**Issue by anuragreddygv323** [skyfielders/python-skyfield#687]

**Comment by brandon-rhodes** [comment]
The dates and positions of the lunar nodes can be calculated using the almanac routine:

https://stackoverflow.com/questions/45909580/longitude-of-lunar-nodes-using-skyfield

To compute culture-specific interpolations of the lunar nodes, you will need to consult a reference work that describes how that particular culture decided to measure the Moon's orbit and position, and then build Python code that re-enacts that computation. The only think Skyfield can tell you is where the Moon and Sun really were; it cannot, alas, be of any assistance in figuring out what human societies computed based on those physical positions.

Since I don't think there are any new Skyfield features needed here, I'll close this issue, but feel free to comment further here if you have trouble getting the Skyfield routine to give you lunar crossings of the equator!

**Comment by anuragreddygv323** [comment]
im calculating the angles between two planets in eph as below

t = ts.utc(2022, 1, 4)
jup,sun,saturn,venus,mars,moon, earth, mercury = eph[5],eph[10],eph[6],eph[299],eph[499], eph[301], eph[399],eph[199]

#Angle between sun and saturn on 01/04/2022
e = earth.at(t)
s = e.observe(sun).apparent()
v = e.observe(saturn).apparent()

s.separation_from(v).degrees


I want to compute the angle between planets and lunar nodes .... can u tell me how ?

**Comment by anuragreddygv323** [comment]
I want to know how to compute the difference between angles between Rahu and SUN

**Comment by anuragreddygv323** [comment]
for Jan 4th 2022 can I get this 

![image](https://user-images.githubusercontent.com/12067206/151075400-d949dbb3-7fb9-41e2-8a8d-f4747aba32fd.png)

**Comment by anuragreddygv323** [comment]
@brandon-rhodes  any suggestions plz

**Comment by brandon-rhodes** [comment]
I don't, alas, have any suggestion, because I don't know how ancient astronomers turned raw observations of the Moon into the position in the sky that they call “Rahu”? All Skyfield can tell you is where the Moon really is. You will have to take those longitudes, and do something to fill in longitudes in the dates where the Moon isn't at its node.
