### ISSUE TITLE
It appears that the 2015 July leap seconds is not shown, but the 2012 one is?

### ISSUE THREAD

**Issue by jamessclarkiv** [skyfielders/python-skyfield#71]
five_seconds = range(58, 58 + 5)
tup = (2015, 6, 30, 23, 59, five_seconds)
jd = JulianDate(utc=tup)

for string in jd.utc_jpl():
    print(string)

**Comment by brandon-rhodes** [comment]
The internal leap-second table is probably out of date! I wonder if I should even ship Skyfield with a table, or always make people download it? I will make a decision one way or the other and get a fix into the next version of Skyfield. Thanks!

**Comment by brandon-rhodes** [comment]
I have just updated the internal leap second table, and I can tell it worked, because a test for a Jovian moon position in the future started failing and I had to move its time back one second. :)

I will be thinking about a way to protect in the future against forgetting to do this update, but for now will close this immediate issue. Thanks for letting me know about it!

**Comment by brandon-rhodes** [comment]
Oh: and, I hope to release a new version of Skyfield soon — but if you need the fix earlier than that, then running

    python -m skyfield.data

should do the update locally on your own copy. Let me know if you have any trouble with that command.
