### ISSUE TITLE
Vector addition and subtraction

### ISSUE THREAD

**Issue by delcompan** [skyfielders/python-skyfield#751]
eph = load('de/de421.bsp')
sun, earth = eph['sun'], eph['earth']
A: print((sun - earth).at(t))      # retrun <Geocentric ICRS position and velocity at date t center=399 target=10>
B: print((earth - sun).at(t))      # retrun <ICRF position and velocity at date t center=10 target=399>
C: print(earth.at(t))                 # retrun <Barycentric BCRS position and velocity at date t center=0 target=399>
D: print(sun.at(t))                    # retrun <Barycentric BCRS position and velocity at date t center=0 target=10>
E: print(sun.at(t).position)      # retrun [-0.008965    0.00182226  0.00099967] au
What is the difference between A and B? Or what is the difference between Geocentric ICRS position and ICRF position?
A barycentric position measures from the Solar System’s center of mass. Why is the return value of E not zero? The solar system's center of mass is not the center of sun?

**Comment by brandon-rhodes** [comment]
> What is the difference between A and B?

The two vectors should be of the same magnitude but point in opposite directions.

> Or what is the difference between Geocentric ICRS position and ICRF position?

The ICRS and ICRF are the same coordinate frame; please point out if there's somewhere Skyfield could be more consistent in using the term ICRS.

> A barycentric position measures from the Solar System’s center of mass. Why is the return value of E not zero? The solar system's center of mass is not the center of sun?

Because there are other masses in the Solar System besides the Sun. The center of mass includes everything in the Solar System, not just the Sun.
