### ISSUE TITLE
Skyfield Not Working in Anaconda Prompt

### ISSUE THREAD

**Issue by TTurmanian** [skyfielders/python-skyfield#794]
I have installed Anaconda Navigator (version 2.1.1), and Skyfield, but when I try to test what version of Skyfield I have using the code from the Skyfield documentation, I get an error saying the '<' sign was not expected.  See screenshot below.

(Skyfield is already installed since running 'pip install skyfield' results in several lines saying 'requirement already satisfied'.

![Skyfield in Anaconda Prompt Window](https://user-images.githubusercontent.com/114183487/191826104-3474e2a1-1d39-404a-ab3d-1b5170723158.PNG)

**Comment by brandon-rhodes** [comment]
You cannot enter Python code at the `>` Windows system prompt, it does not, alas, understand it. You will need to launch the Anaconda Python interpreter—do the instructions tell you how to run it?

**Comment by TTurmanian** [comment]
No, not the Skyfield instructions.  I'm looking at the Anaconda documentation for the Anaconda Python interpreter.

**Comment by TTurmanian** [comment]
By Anaconda Python interpreter, do you mean an IDE like Spyder?  In Spyder, I tried calling skyfield.VERSION from the console , but it returned a 'name 'skyfield' not defined ' error.

**Comment by brandon-rhodes** [comment]
@TTurmanian — I'm catching up on issues after a few busy months, and only just noticed your follow-on questions. Alas, I'm not sure how to answer, as I don't know how your environment is set up. I get a Python prompt by running the `python` or `python3` command at my system prompt. If you have an IDE, you'll want to consult its documentation to learn how to get an interactive Python prompt.

I'm going to close this issue, since Skyfield works fine with both the system prompt and with IDEs, and since my guess is that you probably have gotten it working in the meantime. But feel free to make further comments if there's something you have not gotten working yet—GitHub issues can still receive comments even after they are closed.
