### ISSUE TITLE
Improve how docs explain satellite ‘propagation’

### ISSUE THREAD

**Issue by CiaranMoran1** [skyfielders/python-skyfield#833]
Hi :)
I am trying to generate TLEs from state vectors. As part of this I am propagating existing TLEs using sgp4.api.Satrec. As stated in the documentation the orbital elements of a satellite are given as properties of this object 

```
Mean Elements From Most Recent Propagation

Partway through each propagation, the SGP4 routine saves a set of “singly averaged mean elements” that describe the orbit’s shape at the moment for which a position is being computed. They are averaged with respect to the mean anomaly and include the effects of secular gravity, atmospheric drag, and — in Deep Space mode — of those pertubations from the Sun and Moon that SGP4 averages over an entire revolution of each of those bodies. They omit both the shorter-term and longer-term periodic pertubations from the Sun and Moon that SGP4 applies right before computing each position.

am — Average semi-major axis (earth radii).
em — Average eccentricity.
im — Average inclination (radians).
Om — Average right ascension of ascending node (radians).
om — Average argument of perigee (radians).
mm — Average mean anomaly (radians).
nm — Average mean motion (radians/minute).
```

I need clarification on the functionality of Satrec, in particular what "Partway through each propagation" means in terms of the orbital elements that are produced. Are these orbital elements created at the epoch of propagation or are they created at some point between the original epoch and the propagation epoch? If it is the latter is it possible to determine what epoch they were created at?

Thank you

**Comment by brandon-rhodes** [comment]
Perhaps the documentation can be expanded to better describe the idea of _propagation_ — it does not, as I understand it, move forward or back from the TLE's epoch towards the time the user has asked about; otherwise, propagation would take longer and longer depending on how many days later the user was asking about. Instead, it jumps immediately to the time the user is asking about, and there, for that specific and exact time, it starts making adjustments to the orbit based on how it thinks satellite orbits change over time.

In which case I should rewrite that sentence so that it's clear that ‘partway’ refers to SGP4’s computation, _not_ partway between the epoch and the time being asked about.

Let's leave this issue open until I can get that sentence rewritten in the docs. If anyone understands the steps SGP4 takes in more detail, maybe they can weigh in—in which case, instead of the docs merely saying something like ‘partway through the computation’, we could actually list all the steps SGP4 takes, and then say ‘the elements are produced right here in step 5, and so they reflect all of the adjustments 1–4, but not 6–10’ or whatever. But when I myself have read through the SGP4 code before, I'm often not familiar with the steps it's taking, and so I can't describe what they're trying to accomplish; and the comments are not frequent or verbose enough to help me guess.

**Comment by CiaranMoran1** [comment]
Thank you that is very helpful
Follow up to this question with some more detail.
I'm using sgp4.ext.rv2coe to generate orbital elements from observational state vectors with the end goal of building TLEs from the orbital elements. To verify the accuracy of the outputs from rv2coe I have taken a TLE of the same satellite from space-track.org and back propagated it to the epoch of my state vectors using sgp4.api.Satrec 
The results of these conversions are as follows
```
rv2coe      | Satrec propagation
6761         | 6756        semi-major axis
0.000185 | 0.00044     eccentricity
0.7252     | 0.7238      inclination
2.364       | 2.3719      Longitude of ascending node
0.53         | 5.099       perigee
4.68         | -6.17       mean anomaly
```

I am happy with how well the first four elements line up, they're within a reasonable margin of error. But I am very confused about how they can be so well aligned and the perigee and mean anomaly are so far off. The TLE I have used is being back propagated 5 days to generate these values. Do you have any suggestions on why this might be occurring?

**Comment by brandon-rhodes** [comment]
What units are those perigee and anomaly values—degrees? I don't have a sense for how big a difference they represent, in terms of kilometers in the sky, say for something like 4.68 vs -6.17.

There has also been discussion of building TLEs over on my Skyfield library, which uses `sgp4` internally. Here's one issue that comes to mind on the subject: https://github.com/skyfielders/python-skyfield/issues/457

**Comment by CiaranMoran1** [comment]
No sorry those are in radians, I should have specified

**Comment by brandon-rhodes** [comment]
I finally got around to improving that paragraph in the SGP4 docs:

https://github.com/brandon-rhodes/python-sgp4/commit/8416d166b4001e84fcb68bef04bd22383929591e

The documentation will update on PyPI the next time sgp4 is released.
