### ISSUE TITLE
enhancement for caching values p.ex. in class Time

### ISSUE THREAD

**Issue by voxspox** [skyfielders/python-skyfield#84]
pyramid has a nice decorator called @reify to replace a method with its value once called:

http://docs.pylonsproject.org/projects/pyramid/en/latest/api/decorator.html

check the source, there is a link in the top right corner.

**Comment by brandon-rhodes** [comment]
I realize that I have left this suggestion hanging now for several months! When I get the chance, I will benchmark `reify` against my current solution of `if` statements inside of `__getattr__()`. Since people may someday use this library in performance-sensitive situations, I am likely to go with whichever solution is faster, since I don’t find the `if` statements too difficult to maintain. Thanks for pointing out `reify`, and I will comment here when I finally get time to investigate it!

**Comment by jrs65** [comment]
One point in favour of using `reify` is that it makes the API more discoverable. As a human, at the moment it's hard to figure out bits of the API using ipython/text editor autocompletion (or even an old fashioned `dir`) because they are hidden inside `__getattr__` until they are first used. e.g. if I see `ut1` as an attribute on a `Time` object I'm pretty sure that's how I do the conversion into UT1, but if I don't I need to go and dig out the docs. I don't imagine that I'm the only one who uses this to explore what I can do with a new library.

It's also probably better for static code checking tools like `pylint`.

**Comment by brandon-rhodes** [comment]
Thanks for the recommendation! This was accomplished in f757bc451fe9d19b58cf25ba2407c6eda755db8a and f2e8f11ac36027d246455ac2ac9bbd3a6496eeed.

**Comment by voxspox** [comment]
:+1: :smiley:
