### ISSUE TITLE
can i use skyfield to calcuate orbital elements from state vector?

### ISSUE THREAD

**Issue by onetwothreeapple** [skyfielders/python-skyfield#846]

**Comment by brandon-rhodes** [comment]
Here are some issues where this has been discussed — hopefully one of them will be helpful, since I remember folks offering links to code they had written to compute orbits:

https://github.com/skyfielders/python-skyfield/issues/278
https://github.com/skyfielders/python-skyfield/issues/457
https://github.com/brandon-rhodes/python-sgp4/issues/86
