### ISSUE TITLE
"photoplate" methods?

### ISSUE THREAD

**Issue by davidmikolas** [skyfielders/python-skyfield#88]
Maybe it's best just to leave this to the user, but some kind of "photoplate" method might be kind-of useful (although it's hard to imagine a one-size-fits-all approach)

This is the transit of Mercury coming (around May 9, 2016).

Am I using the best possible methods? And using them correctly?

I've pasted the script below the screenshot. Skyfield is so darn fun!

![image](https://cloud.githubusercontent.com/assets/17236804/15091217/60853786-1474-11e6-8235-6a4144709d34.png)

```
def photoplate_altaz(altaz_ref, altaz_data):

    y = altaz_data[0].radians - altaz_ref[0].radians

    xmag = np.cos(altaz_ref[0].radians)

    x = xmag * (altaz_data[1].radians - altaz_ref[1].radians)

    return x, y


def photoplate_radec(radec_ref, radec_data):

    y = radec_data[1].radians - radec_ref[1].radians 

    xmag = np.cos(radec_ref[1].radians )

    x = xmag*(radec_data[0].radians - radec_ref[0].radians)

    return x, y


from skyfield.api import load
import numpy as np
import matplotlib.pyplot as plt

pi, twopi = np.pi, 2.*np.pi

r_sun  = 695700.  # approx
r_merc = 2440.    # just a guess

data = load('de421.bsp')

sun     = data['sun']
mercury = data['mercury']
earth   = data['earth']

ts   = load.timescale()

daze = np.linspace(9.4, 9.8, 41)[8:-2]  # just some points for now

t    = ts.utc(2016, 5, daze)

del_Teide = earth.topos(28.3, -16.5, elevation_m = 2390.)  # observatory

merc_app = del_Teide.at(t).observe(mercury).apparent()
sun_app  = del_Teide.at(t).observe(sun).apparent()

app_sep  = merc_app.separation_from(sun_app).radians

sundist  = sun_app.distance().km

sun_rad  = np.arctan2(r_sun, sundist)

# draw the sun, just use the apparent size at the beginning
th       = np.linspace(0, twopi, 101)
xsd, ysd = sun_rad[0]*np.cos(th), sun_rad[0]*np.sin(th)

# ok now generate photoplate coordinates
xaa, yaa = photoplate_altaz(sun_app.altaz(), merc_app.altaz())
xrd, yrd = photoplate_radec(sun_app.radec(), merc_app.radec())

am = 60. * 180. / pi   # radians to arcmin

plt.figure(figsize=[12, 6])

plt.subplot(1, 2, 1)
plt.plot(am*xaa, am*yaa)
plt.plot(am*xaa, am*yaa, 'ok')
plt.plot(am*xsd, am*ysd, '-k')
plt.title('altaz - zenith is up', fontsize=18)

plt.subplot(1, 2, 2)
plt.plot(am*xrd, am*yrd)
plt.plot(am*xrd, am*yrd, 'ok')
plt.plot(am*xsd, am*ysd, '-k')
plt.title('radec - north is up', fontsize=18)

plt.show()
```

**Comment by brandon-rhodes** [comment]
Yes, I would eventually like Skyfield to have the ability to help users create diagrams of things like conjunctions and occultations! I might not have time to look at this for several weeks, but hopefully after PyCon I will get the time to look at your code in more detail. Thanks!

**Comment by brandon-rhodes** [comment]
At long last, Skyfield now has a large enough collection of features that you can now use the library to, say, draw a full finder chart for comet NEOWISE!

https://rhodesmill.org/skyfield/example-plots.html#drawing-a-finder-chart-for-comet-neowise

![image](https://user-images.githubusercontent.com/166162/88381802-1d05ab80-cd75-11ea-915a-987287a7c402.png)

Users can now start from the example script and adapt it to produce whatever plots they wish. Over time I plan to accumulate more examples showing, for example, how to draw the horizon, or orient the plot to an altazimuth grid rather than having north at the top.

The big decision here is that Skyfield is not going to include plotting code of its own — there are two many plotting libraries and output devices for Skyfield to choose one official solution, and far too many parameters that need to be passed to every element of a plot (color, alpha channel, marker) to usefully bundle up “draw a chart” into a single callable that would somehow take all those settings as parameters. Instead, Skyfield is instead going to stay out of the plotting business, and simply provide users with example scripts that they can adapt to their own needs — with Skyfield providing coordinates, but never calling the plotting functions themselves.

Feel free to comment further here with ideas, but I am going to close this in the meantime, as I believe the NEOWISE script now minimally satisfies the need for a way to plot Skyfield coordinates. Enjoy!
