### ISSUE TITLE
Sun and Moon, find date and time of  crossing a specific longitude

### ISSUE THREAD

**Issue by tutucea** [skyfielders/python-skyfield#897]
given that  it takes 29 day for the moon to do a full loop and considering that the moon is at ```43.1241 degrees``` can we calculate when the moon reaches ```43.1074 degrees``` for the next two months ?

also can we calculate the same for the sun ?  this is right now ```43.1472 degrees```
What date and time it will reach those coordinates again ?( given its a year away) 
The Moon and the Sun do not go on retrogrades so calculating such a thing should be easy, no ?

i did look thru this and i haven't found anything that allows one to enter the coordinates https://github.com/skyfielders/python-skyfield/blob/a7d7a2a2d163fa9f5731fbfeb4e71cccdef03b6e/skyfield/documentation/searches.rst

**Comment by brandon-rhodes** [comment]
Take a look at https://rhodesmill.org/skyfield/searches.html — it should explain how to set up search criteria of your own! I'm going to close this issue, because those instructions should let you tell Skyfield to search for whatever circumstances you want; but please feel free to comment further on this issue (you can comment even if it's closed!) with more questions if you have them after reading that documentation. Maybe it will lead to the documentation being improved!
