### ISSUE TITLE
Can't create times in Universal Time

### ISSUE THREAD

**Issue by voronY** [skyfielders/python-skyfield#91]
`t = ts.ut1(jd=2788977)`
`AttributeError: 'Timescale' object has no attribute 'ut1'`
Skyfield 0.8 installed with pip. Works 'ok' with tai, tt and tdb.

**Comment by brandon-rhodes** [comment]
This one is going to be interesting: since the TT–UT1 difference is looked up by TT, I suspect that a `ut1()` method will have to iterate until it finds an acceptable TT. Which will involve a Boolean mask over the array of times provided that lets me keep iterating on the ones that are still converging.

But there is a similar loop over in the code that does light round-trip times, so I'll see what I can do! I might get some time to work on Skyfield this weekend.
